(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./engine.js'):root.FlyingReview);if(typeof module==='object'&&module.exports)module.exports=api;else root.BaslerReview=api;})(globalThis,function(F){
'use strict';
const spec=Object.freeze({camera:'Basler a2A2600-20gcBAS',sensor:'Gpixel GMAX2505',shutter:'Global Shutter',pixelUm:2.5,mag:20,width:2600,height:2128,fullHeight:2160,fps:18.5,minExposure:2,maxExposure:10000000,objective:'Mitutoyo 378-810-3 M Plan Apo SL20X',na:.28,wd:30.5,resolutionUm:1,dofUm:3.5});
const controls=['exposureUs','blurPx','vx','ax','dx','vy','ay','dy'];
const defaults={exposureUs:2,blurPx:2,vx:200,ax:1000,dx:1000,vy:100,ay:500,dy:500};
function parameters(input={}){const a={...defaults,...input};for(const k of controls)if(!Number.isFinite(a[k])||a[k]<=0)throw Error(k+'는 0보다 큰 숫자여야 합니다.');const p=F.copyDefaults();for(const k of controls)if(k!=='blurPx')p[k]=a[k];p.maxBlurUm=a.blurPx*spec.pixelUm/spec.mag;return p;}
function select(cap,p,g){if(![2,4].includes(cap))throw Error('기판당 2점 또는 4점만 선택합니다.');const used=new Set(),defs=[];for(let h=1;h<=8;h++){const target=((h-1)%cap)*p.cellPitchY;const candidates=g.byHead[h].filter(n=>!used.has(n.cell)).sort((a,b)=>Math.abs(g.cells[a.cell-1].offsetY-target)-Math.abs(g.cells[b.cell-1].offsetY-target)||a.cell-b.cell||a.row-b.row||a.col-b.col);let chosen=null;for(const r of candidates){const d={head:h,cell:r.cell,col:r.col,row:r.row,beam:7,enabled:true};if(F.makePoint(d,p,g).geometryValid){chosen=d;break;}}if(!chosen)throw Error('H'+h+'의 중복되지 않는 유효 Cell을 찾지 못했습니다.');defs.push(chosen);used.add(chosen.cell);}return defs;}
function analyze(input={},defs=null){const p=parameters(input),g=F.makeGeometry(p),points=defs||select(4,p,g);if(points.length!==8||new Set(points.map(d=>d.head)).size!==8||points.some(d=>d.enabled===false))throw Error('Scanner 1~8에 각각 1점이 필요합니다.');if(new Set(points.map(d=>d.cell)).size!==8)throw Error('서로 다른 Scanner는 반드시 서로 다른 Cell을 선택해야 합니다.');const r=F.buildState(p,points,g),modes={};for(const cap of [2,4]){const groups=[];for(let i=0;i<8;i+=cap)groups.push(F.passFor(r.nodes.slice(i,i+cap),r));modes[cap]={cap,count:8/cap,groups,valid:groups.every(z=>z.valid),minimumSlack:Math.min(...groups.map(z=>z.slack))};}return {input:{...defaults,...input},p,g,defs:points,r,modes,blurPx:p.vy*p.exposureUs/(1000*(spec.pixelUm/spec.mag)),exposureLimitUs:input.blurPx===undefined?defaults.blurPx*125/p.vy:input.blurPx*125/p.vy,vyBlurLimit:(input.blurPx??defaults.blurPx)*125/p.exposureUs};}
function coverage(a,cap,time,previous=[]){const done=new Set(previous),r=a.r,span=r.profile.total+1;const mode=a.modes[cap],index=Math.min(mode.count-1,Math.max(0,Math.floor(time/span))),local=Math.min(span,time-index*span);for(let i=0;i<=index;i++)if(mode.groups[i].valid)for(const n of mode.groups[i].nodes)if(i<index||local>=n.expEnd+r.jitter)done.add(n.head);return {done:[...done].sort((x,y)=>x-y),index,local,span,total:span*mode.count,complete:done.size===8};}
function suggestions(a,cap){if(a.modes[cap].valid)return [{text:'선도착·등속·Blur 조건을 계산상 충족합니다. 조명과 실제 영상 판정은 별도 확인합니다.'}];const tips=[];if(a.blurPx>a.input.blurPx+1e-5){const t=Math.floor(a.exposureLimitUs*1000)/1000;if(t>=2)tips.push({text:'노출을 '+t+' µs 이하로 낮추세요. 밝기 부족 여부도 확인하세요.',patch:{exposureUs:t}});else tips.push({text:'필요 노출 '+t+' µs는 최소 2 µs보다 짧습니다. Y 속도를 '+a.vyBlurLimit.toFixed(2)+' mm/s 이하로 낮추세요.',patch:{vy:a.vyBlurLimit}});}if(cap===4&&a.modes[2].valid)tips.push({text:'같은 좌표를 2점씩 나누면 4 Glass로 운영할 수 있습니다.',mode:2});const es=a.modes[cap].groups.flatMap(z=>z.edges);if(es.some(e=>e.xSlack<0)){const values=es.map(e=>F.minVelocity(e.dx,e.xAvailable,a.p.ax,a.p.dx));const found=values.every(Number.isFinite)?Math.max(...values):null;if(Number.isFinite(found))tips.push({text:'구간 X 속도 약 '+found.toFixed(1)+' mm/s 이상이 필요합니다. 적용 후 초기 이동·복귀·전체 조건까지 재계산하세요.',patch:{vx:Math.ceil(found)}});else tips.push({text:'X 속도만 높여도 해결되지 않습니다. X 가감속을 높이거나 대표점 Y 간격을 넓히세요.'});}if(a.r.globals.length)tips.push({text:a.r.globals.join(' / ')+'. Y 감속 시 Tact가 늘고, Y 가감속이 작으면 등속구간이 줄어듭니다.'});if(!tips.length)tips.push({text:'아래 구간 표의 불가 원인을 확인하세요. 같은 Y 점은 다른 기판으로 나누거나 대표점을 다른 행으로 옮겨야 합니다.'});return tips;}
return {spec,controls,defaults,parameters,select,analyze,coverage,suggestions};
});
