(function(){'use strict';const B=BaslerReview,F=FlyingReview,$=id=>document.getElementById(id);let input={...B.defaults},defs=null,a,cap=4,time=0,done=[],running=false,last=null,cycle=1,selected=1;
const fmt=(x,n=2)=>Number.isFinite(x)?x.toFixed(n):'—';const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={exposureUs:'노출시간 (µs)',blurPx:'허용 Blur (pixel)',vx:'Review X 속도',ax:'X 가속',dx:'X 감속',vy:'Stage Y 속도',ay:'Y 가속',dy:'Y 감속'};
$('inputs').innerHTML=B.controls.map(k=>`<label>${labels[k]}<input id="param-${k}" data-param="${k}" type="number" min="${k==='exposureUs'?2:.001}" step="any" value="${input[k]}"></label>`).join('');$('selectedHead').innerHTML=Array.from({length:8},(_,i)=>`<option value="${i+1}">H${i+1}</option>`).join('');
function reset(){running=false;last=null;time=0;done=[];cycle=1;draw();}
function calculate(resetCycle=true){try{a=B.analyze(input,defs);defs=a.defs;$('error').hidden=true;$('export').disabled=false;if(resetCycle){time=0;done=[];running=false;cycle=1;}render();draw();return true;}catch(e){running=false;$('error').hidden=false;$('error').textContent=e.message;$('play').disabled=true;$('export').disabled=true;$('narrative').textContent='입력 또는 대표점 오류입니다. 이전 계산 화면은 참고용으로만 유지합니다.';return false;}}
function table(headers,rows){return `<table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
function render(){const m=a.modes[cap],r=a.r;$('play').disabled=!m.valid;document.querySelectorAll('[data-cap]').forEach(b=>b.classList.toggle('active',Number(b.dataset.cap)===cap));$('summary').innerHTML=[['선택 운영',m.valid?`${cap}점 계산상 가능`:'현재 조건 불가',m.valid?'good':'bad'],['이동 Blur',`${fmt(a.blurPx)} / ${fmt(input.blurPx)} px`,a.blurPx<=input.blurPx+1e-5?'good':'bad'],['8 Scanner 대표점 커버',m.valid?`${m.count} Glass / 사이클`:'조건 변경 필요',m.valid?'good':'bad'],['가공 / 예시 Tact',`${fmt(r.processTime,1)} / ${fmt(r.tact,1)} s`,r.globals.length?'bad':'good']].map(([k,v,c])=>`<div class="metric">${k}<b class="${c}">${v}</b></div>`).join('');
$('comparison').innerHTML=[2,4].map(k=>{const z=a.modes[k];return `<div class="compare"><b>${k}점/Glass · ${z.valid?'가능':'불가'}</b><p>${z.groups.map((g,i)=>'G'+(i+1)+': '+g.nodes.map(n=>'H'+n.head).join('·')).join(' / ')}</p><p>${z.valid?`${z.count} Glass로 8개 대표점을 1회 커버`: '8개 대표점의 전체 커버를 보장하지 못합니다.'}</p></div>`;}).join('');
const tips=B.suggestions(a,cap);$('advice').innerHTML=tips.map((t,i)=>`<p>${esc(t.text)}${t.patch||t.mode?`<button data-tip="${i}">변경 후 재계산</button>`:''}</p>`).join('');$('advice').querySelectorAll('[data-tip]').forEach(b=>b.onclick=()=>{const t=tips[Number(b.dataset.tip)];if(t.patch){Object.assign(input,t.patch);sync();}if(t.mode)cap=t.mode;calculate();});
$('timing').innerHTML=table(['Glass / 구간','ΔX / ΔY (mm)','다음 점 도착','X 가감속 이동','준비 필요 / 여유','판단'],m.groups.flatMap((g,i)=>g.edges.map(e=>[`G${i+1} H${e.a}–H${e.b}`,`${fmt(e.dx,1)} / ${fmt(e.dy,1)}`,`${fmt(e.gap,3)} s`,`${fmt(e.move,3)} s`,`${fmt(e.need,6)} / ${fmt(e.xSlack,3)} s`,`<span class="${e.valid?'good':'bad'}">${e.valid?'가능':esc(e.reasons.join(', '))}</span>`])));
$('pointTable').innerHTML=table(['Scanner','서로 다른 Cell','Shot / DOE','Global X / Y (mm)','Review 시점','개별 조건'],r.nodes.map(n=>['H'+n.head,'C'+n.cell,n.shot+' / B'+n.beam,fmt(n.x,3)+' / '+fmt(n.y,3),fmt(n.cross,3)+' s',n.valid?'충족':esc(n.errors.join(', '))]));}
function sync(){B.controls.forEach(k=>$('param-'+k).value=input[k]);}
function draw(){if(!a)return;const c=B.coverage(a,cap,time,done);done=c.done;const r=a.r,group=a.modes[cap].groups[c.index],state=r.profile.at(c.local),cam=F.cameraPath(group,a.p).at(c.local);const active=new Set(group.nodes.map(n=>n.head));const valid=group.valid;const next=group.nodes.find(n=>c.local<n.expEnd+r.jitter);const phase=state.phase;
$('play').textContent=running?'Ⅱ 일시정지':'▶ 재생';$('clock').textContent=`사이클 ${cycle} · G${c.index+1}/${a.modes[cap].count} · ${fmt(c.local,1)} s`;$('seek').value=Math.min(1000,time/c.total*1000);$('ledger').innerHTML=r.nodes.map(n=>`<div class="head ${done.includes(n.head)?'done':active.has(n.head)?'current':''}">H${n.head} · C${n.cell}<br>${done.includes(n.head)?'취득 유지':active.has(n.head)?'이번 기판':'다음 기판'}</div>`).join('');
let narration=!valid?'현재 조건은 취득 불가입니다. 조건을 변경하고 재계산하세요.':c.complete?'8개 Scanner 대표점 취득 사이클을 완료했습니다. 완료 표시는 다음 사이클 시작 전까지 유지합니다.':phase==='가속'||phase==='감속'?`Y축 ${phase} 중입니다. 이 구간에서는 촬영하지 않습니다.`:next?`G${c.index+1}: ${cam.phase}. 다음은 H${next.head}, C${next.cell}이며 ${fmt(Math.max(0,next.cross-c.local),2)}초 후 Review 위치를 통과합니다.`:`G${c.index+1} 취득 완료. X축 복귀와 다음 기판 통과를 기다립니다.`;$('narrative').textContent=narration;
const s=.30,mx=55,reviewY=610,mapX=635,mapY=120,ms=.30;const xx=x=>mx+x*s,yy=y=>reviewY-(state.q+y-a.p.akY)*s;let svg=`<defs><clipPath id="machineClip"><rect x="25" y="25" width="515" height="625"/></clipPath></defs><text x="45" y="27" font-size="18" fill="#173449">실제 거리 기준 이동 장면</text><text x="580" y="27" font-size="18" fill="#173449">45 Cell · 사이클 누적 지도</text><text x="580" y="52" font-size="13" fill="#607585">지도에서 위치를 클릭해 대표점 변경</text><g clip-path="url(#machineClip)">`;
svg+=`<rect x="${mx}" y="${yy(a.p.glassY)}" width="${a.p.glassX*s}" height="${a.p.glassY*s}" fill="#eaf4fb" stroke="#8fb7d0" stroke-width="2"/>`;
for(const cell of a.g.cells){svg+=`<rect x="${xx(cell.x)}" y="${yy(cell.y+cell.height)}" width="${cell.width*s}" height="${cell.height*s}" fill="white" stroke="#bed2dc"/><text x="${xx(cell.x)+2}" y="${yy(cell.y+cell.height)+10}" font-size="8" fill="#607585">C${cell.id}</text>`;for(const h of cell.model.holes.slice(0,cell.model.holeCount))if(h[2]>0&&h[3]>0)svg+=`<rect x="${xx(cell.x+h[0]+a.g.half)}" y="${yy(cell.y+h[1]+h[3]+a.g.half)}" width="${h[2]*s}" height="${h[3]*s}" fill="#edc9c3"/>`;}
for(const n of r.nodes){const color=done.includes(n.head)?'#157957':active.has(n.head)?'#087f8c':'#bac8d0';svg+=`<circle cx="${xx(n.x)}" cy="${yy(n.y)}" r="5" fill="${color}"/><text x="${xx(n.x)+6}" y="${yy(n.y)-7}" font-size="12" fill="${color}">H${n.head}</text>`;}
for(let h=1;h<=8;h++){const hx=a.p.akX+a.p.head1AKX+(h-1)*110-10,hy=reviewY-(1467+(h%2===0?380:0))*s;svg+=`<rect x="${xx(hx)-12}" y="${hy-10}" width="24" height="20" rx="3" fill="#d5914e"/><text x="${xx(hx)}" y="${hy+4}" text-anchor="middle" font-size="11" fill="white">${h}</text>`;}
svg+=`<text x="350" y="62" font-size="13" fill="#9d6c39">Scanner 2·4·6·8</text><text x="350" y="174" font-size="13" fill="#9d6c39">Scanner 1·3·5·7</text><path d="M370 285 V380 l-8 -13 m8 13 l8 -13" fill="none" stroke="#8fb7d0" stroke-width="3"/><text x="390" y="315" font-size="13" fill="#607585">Stage −Y</text><text x="390" y="340" font-size="13" fill="#607585">기판 통과</text><line x1="40" x2="400" y1="${reviewY}" y2="${reviewY}" stroke="#087f8c" stroke-width="3"/><rect x="${xx(cam.x+a.p.akX)-13}" y="${reviewY-19}" width="26" height="38" rx="4" fill="#087f8c"/><text x="410" y="${reviewY-12}" font-size="13" fill="#087f8c">ATM Box</text><text x="410" y="${reviewY+7}" font-size="13" fill="#087f8c">Review X</text></g><text x="45" y="675" font-size="13" fill="#607585">Y ${fmt(state.v,1)} mm/s · ${phase} / X ${fmt(Math.abs(cam.v),1)} mm/s</text>`;
svg+=`<g id="globalMap"><rect x="${mapX}" y="${mapY}" width="${a.p.glassX*ms}" height="${a.p.glassY*ms}" fill="#f3f8fb" stroke="#8fb7d0" stroke-width="2"/>`;
for(const cell of a.g.cells)svg+=`<rect x="${mapX+cell.x*ms}" y="${mapY+cell.y*ms}" width="${cell.width*ms}" height="${cell.height*ms}" fill="${r.nodes.some(n=>n.cell===cell.id)?'#d8edf0':'white'}" stroke="#b4cbd8"/><text x="${mapX+cell.x*ms+1}" y="${mapY+cell.y*ms+10}" font-size="8" fill="#607585">${cell.id}</text>`;
for(const n of r.nodes){const color=done.includes(n.head)?'#157957':active.has(n.head)?'#087f8c':'#899ca8';svg+=`<circle cx="${mapX+n.x*ms}" cy="${mapY+n.y*ms}" r="7" fill="${color}" stroke="white"/><text x="${mapX+n.x*ms+9}" y="${mapY+n.y*ms-6}" font-size="14" font-weight="700" fill="${color}">H${n.head}</text>`;}
svg+=`</g><text x="580" y="625" font-size="14" fill="#157957">녹색: 취득 이력 ${done.length}/8 (실제 영상 PASS 아님)</text><text x="580" y="650" font-size="13" fill="#607585">Global 좌표 mm / 원본 PPID 9열×5행</text>`;
const xml=new DOMParser().parseFromString('<svg xmlns="http://www.w3.org/2000/svg">'+svg+'</svg>','image/svg+xml');$('scene').replaceChildren(...Array.from(xml.documentElement.childNodes).map(n=>document.importNode(n,true)));
}
$('inputs').addEventListener('change',e=>{const k=e.target.dataset.param;if(k){input[k]=Number(e.target.value);calculate();}});document.querySelectorAll('[data-cap]').forEach(b=>b.onclick=()=>{cap=Number(b.dataset.cap);calculate();});$('defaults').onclick=()=>{input={...B.defaults};defs=null;sync();calculate();};$('auto').onclick=()=>{defs=null;calculate();$('pointMessage').textContent='8개 서로 다른 Cell의 기본 대표점을 적용했습니다.';};$('selectedHead').onchange=e=>selected=Number(e.target.value);$('restart').onclick=reset;$('play').onclick=()=>{if(!a.modes[cap].valid)return;if(time>=B.coverage(a,cap,time).total){time=0;done=[];cycle++;}running=!running;last=null;draw();};$('seek').oninput=e=>{running=false;time=Number(e.target.value)/1000*B.coverage(a,cap,0).total;draw();};
$('scene').addEventListener('click',e=>{const rect=$('scene').getBoundingClientRect(),x=(e.clientX-rect.left)*1040/rect.width,y=(e.clientY-rect.top)*690/rect.height;if(x<635||x>912.5||y<120||y>570)return;const gx=(x-635)/.30,gy=(y-120)/.30;const used=new Set(defs.filter(d=>d.head!==selected).map(d=>d.cell));let best=null;for(const v of a.g.byHead[selected]){if(used.has(v.cell))continue;const def={head:selected,cell:v.cell,col:v.col,row:v.row,beam:7,enabled:true},point=F.makePoint(def,a.p,a.g);if(!point.geometryValid)continue;const distance=Math.hypot(point.x-gx,point.y-gy);if(!best||distance<best.distance)best={def,distance};}if(best){defs=defs.map(d=>d.head===selected?best.def:d);calculate();$('pointMessage').textContent='H'+selected+'을 C'+best.def.cell+'로 변경했습니다. 중복 Cell과 Mask 가공점은 제외했습니다.';}});
$('export').onclick=()=>{const data={camera:B.spec,inputs:input,fixed:a.p,points:defs,results:{blurPx:a.blurPx,process_s:a.r.processTime,tact_assumption_s:a.r.tact,modes:{2:a.modes[2].valid,4:a.modes[4].valid}},disclaimer:'명목 검토. 실효 배율·노출·조명·영상 판정 실측 필요.'};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='FlyingReview_Basler_conditions.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function tick(now){if(running&&a){if(last!==null)time+=(now-last)/1000*Number($('speed').value);last=now;const total=B.coverage(a,cap,0).total;if(time>=total){time=total;draw();if($('loop').checked){time=0;done=[];cycle++;last=null;}else running=false;}draw();}else last=null;requestAnimationFrame(tick);}calculate();requestAnimationFrame(tick);window.FlyingReviewApp={getState:()=>({a,cap,time,done:[...done],cycle}),seek:t=>{time=t;draw();},setMode:k=>{cap=k;calculate();},setInput:v=>{Object.assign(input,v);sync();calculate();},setPoints:d=>{defs=d;return calculate();},restart:reset};
})();
