(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ReviewExplain=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';const f=(n,k=3)=>Number.isFinite(n)?n.toFixed(k):'—',head=h=>'H'+String(h).padStart(2,'0');
function worst(g){return g.edges.reduce((a,b)=>!a||b.slack<a.slack?b:a,null);}
function analyze(c,r,mode,glass,E){const m=r.modes[mode],g=m.groups[glass],e=worst(g),blurPass=r.blurPx<=r.p.blurPx+1e-8,exposurePass=r.p.exposureUs>=c.minExposureUs&&r.p.exposureUs<=c.maxExposureUs;
 const checks=[{key:'time',title:'① 역방향30초',pass:r.processTimePass,value:f(r.processTime)+'s / 30s',note:'가감속 포함'},{key:'y',title:'② Y 등속 후보점',pass:g.reviewFits,value:g.yCandidateCount+' / '+g.nodes.length+'점',note:'Y 범위만 확인 · 촬영완료 수량 아님'},{key:'blur',title:'③ 이동 blur·노출',pass:blurPass&&exposurePass,value:f(r.blurPx,2)+'px / 허용'+f(r.p.blurPx,2)+'px',note:exposurePass?'노출 '+f(r.p.exposureUs,1)+'µs':'카메라 노출범위 밖'},{key:'x',title:'④ X 준비·취득 간격',pass:g.xTimingValid,value:e.valid?'최소 여유 '+f(e.slack)+'s':'부족 '+f(-e.slack)+'s',note:head(e.from)+'→'+head(e.to)+' · 다음 점 '+f(e.gap)+'s'}];
 let headline;if(g.feasible)headline=m.feasible?'이번 기판과 전체 순환 조건을 통과했습니다.':'이번 기판은 가능하지만, 다른 기판의 조건이 불충족입니다.';else if(!e.valid&&r.globalErrors.length===0&&g.nodes.every(n=>n.errors.length===0))headline='30초·Y 후보점·blur는 통과하지만, '+head(e.from)+'→'+head(e.to)+' 준비가 '+f(-e.slack)+'초 늦습니다.';else headline='불충족 조건을 각각 확인해야 합니다: '+g.errors.join(' / ');
 const alt=E.calculate({...c,points:c.comparisonPoints||c.points},r.p),ag=alt.modes[mode].groups[glass],ae=ag.edges.find(a=>a.from===e.from&&a.to===e.to),before=g.nodes.find(n=>n.head===e.to),after=ag.nodes.find(n=>n.head===e.to),offset=Math.abs(after.targetQ-before.targetQ);
 return {m,g,e,checks,headline,alt,ag,ae,offset,cameraLimited:e.needCamera>e.needX,missDistanceMm:Math.max(0,-e.slack)*r.p.vy,readyTime:g.nodes.find(n=>n.head===e.from).expStart+e.need,deadlineTime:g.nodes.find(n=>n.head===e.to).expStart};
}
function checkHtml(d){return d.checks.map(k=>`<div class="checkcard ${k.pass?'checkpass':'checkfail'}" data-check="${k.key}"><div class="topbar"><b>${k.title}</b><span class="pill ${k.pass?'ok':'bad'}">${k.pass?'통과':'불가'}</span></div><strong>${k.value}</strong><span>${k.note}</span></div>`).join('');}
function detailHtml(c,r,d){const e=d.e;return `<b>현재 고정 선정점 기준:</b> 기판1500mm의 등속 가공거리와, 촬영점 사이 X 준비시간은 별도 조건입니다.<br><b>${head(e.from)} 촬영 후, ${head(e.to)}는 ${f(e.gap)}초 뒤 도착합니다.</b><br>${d.cameraLimited?'카메라 재취득':'X 이동·정착'} 준비에는 ${f(e.need,6)}초가 필요해 ${e.valid?'여유 '+f(e.slack,6)+'초':'부족 '+f(-e.slack,6)+'초'}입니다.<br><span class="small">명목 ${head(e.to)} 노출 시작 ${f(d.deadlineTime)}초 / 준비 예산 종료 ${f(d.readyTime)}초. 가공 Stroke 종료 ${f(r.processTime)}초와 별개의 촬영 마감입니다.${!e.valid?' 늦게 준비되면 목표점은 Y '+f(d.missDistanceMm,3)+'mm 더 이동합니다.':''}</span>`;}
function rowsHtml(r,mode){return r.modes[mode].groups.flatMap((g,i)=>g.edges.map(e=>`<tr class="${e.valid?'':'failedrow'}"><td>${i+1}매 / ${head(e.from)}→${head(e.to)}</td><td>${f(e.dx,1)} / ${f(e.dy,1)}</td><td>${f(e.gap)}</td><td>${f(e.move)}</td><td>${f(e.need)}</td><td>${e.valid?'여유 '+f(e.slack):'부족 '+f(-e.slack)}</td><td>${e.valid?'통과':e.needX>e.gap?'X 준비 부족':'카메라 주기 부족'}</td></tr>`)).join('');}
function compareHtml(r,d){if(d.offset<1e-8)return '이 구간에는 측정점 재선정 비교가 적용되지 않습니다. H04·H08이 포함된 기판에서 비교할 수 있습니다.';return `<b>동작조건 그대로, ${head(d.e.to)}만 같은 Cell의 다른 유효점으로 재선정하는 예시</b><br>리뷰에 ${f(d.offset,1)}mm 더 늦게 도착하는 점 → ΔY ${f(d.e.dy,1)}→${f(d.ae.dy,1)}mm, 간격 ${f(d.e.gap)}→${f(d.ae.gap)}초<br>준비시간 ${f(d.ae.need)}초, ${d.ae.valid?'여유 '+f(d.ae.slack*1000,1)+'ms':'부족 '+f(-d.ae.slack*1000,1)+'ms'} · 비교 기판 ${d.ag.feasible?'명목상 가능':'다른 조건까지 확인 필요'}<br><span class="small">이 비교는 현재 선정점에 자동 적용되지 않습니다. 8개 Cell은 모두 다르며, 정착50ms·Guard20ms를 포함한 계산입니다. 실제 여유는 장비에서 확인해야 합니다.</span>`;}
return {worst,analyze,checkHtml,detailHtml,rowsHtml,compareHtml};
});
