using System.IO;
using System.Collections;
using System.Globalization;
using System.Reflection;
using System.Runtime.Loader;
using System.Text.Json;
using Drilling.Common.Managers;
using Drilling.Common.Recipe;
using Drilling.Common.Review;
using Drilling.Common.Station;
using Drilling.File.JHMI;
using Drilling.File.ReviewOffset;
using Drilling.UI;
using Drilling.UI.Menu.Menus;

var root = Path.GetFullPath(args[0]);
var config = Path.Combine(root, "Config");
var recipe = await new CJhmiRecipeFile(config).Find("test0929") ?? throw new Exception("recipe not found");
var settings = new CSettingFile(config);
var parameters = recipe.Parameters.GroupBy(p => p.Key, StringComparer.OrdinalIgnoreCase).ToDictionary(g => g.Key, g => g.Last().Value, StringComparer.OrdinalIgnoreCase);
foreach (var tab in new[] { EN_SETTING_TAB.Option, EN_SETTING_TAB.Motor })
    foreach (var value in settings.Load(tab)) parameters[value.Key] = value.Value;
parameters["HEAD_COUNT"] = "8";
var checks = new List<object>();
void Check(string name, bool condition, object? detail = null) { checks.Add(new { name, passed = condition, detail }); if (!condition) throw new Exception("Assertion failed: " + name); }
bool Eq(double a, double b) => Math.Abs(a-b) < 1e-7;
var plan = CShotCoordinatePlanBuilder.Build(parameters);
var basePoint = plan.Shots.First();
var alc = new AssemblyLoadContext("old-coordinate-builder", true);
alc.Resolving += (context, name) => { var file = Path.Combine(Path.GetDirectoryName(args[1])!, name.Name + ".dll"); return File.Exists(file) ? context.LoadFromAssemblyPath(file) : null; };
var oldAssembly = alc.LoadFromAssemblyPath(Path.GetFullPath(args[1]));
var oldPlan = oldAssembly.GetType("Drilling.Common.Recipe.CShotCoordinatePlanBuilder")!.GetMethod("Build")!.Invoke(null, new object[] { parameters })!;
var oldPoints = ((IEnumerable)oldPlan.GetType().GetProperty("Shots")!.GetValue(oldPlan)!).Cast<object>().ToArray();
double OldValue(object point, string property) => (double)point.GetType().GetProperty(property)!.GetValue(point)!;
Check("zero_new_offsets_preserve_all_coordinate_values", oldPoints.Length == plan.Shots.Count && plan.Shots.Select((p,i) => Eq(p.ScannerGx,OldValue(oldPoints[i],"ScannerGx")) && Eq(p.ScannerGy,OldValue(oldPoints[i],"ScannerGy")) && Eq(p.EncoderWaitPosition,OldValue(oldPoints[i],"EncoderWaitPosition"))).All(x => x), new { points = plan.Shots.Count });
var head = basePoint.HeadNo;
var modified = new Dictionary<string,string>(parameters, StringComparer.OrdinalIgnoreCase) { ["SHIFT_OFFSET_X"]="2", ["SHIFT_OFFSET_Y"]="3", [$"H{head:00}_FIRST_BEAM_OFFSET_X"]="0.4", [$"H{head:00}_FIRST_BEAM_OFFSET_Y"]="0.5" };
var shifted = CShotCoordinatePlanBuilder.Build(modified).Shots.Single(p => p.HeadNo == head && p.ShotKey == basePoint.ShotKey);
var transform = CScannerAxisTransform.Read(parameters,head);
var direction = double.Parse(parameters["STAGE_SCAN_DIRECTION_Y"],CultureInfo.InvariantCulture);
var shiftDelta = transform.Apply(2,3*direction);
var beamDelta = transform.Apply(0.4,-0.5);
var scale = double.Parse(parameters[$"H{head:00}_ENCODER_SCALE"],CultureInfo.InvariantCulture);
Check("shift_and_first_beam_transform", Eq(shifted.ScannerGx-basePoint.ScannerGx,shiftDelta.X+beamDelta.X) && Eq(shifted.ScannerGy-basePoint.ScannerGy,shiftDelta.Y+beamDelta.Y), new { head, dx=shifted.ScannerGx-basePoint.ScannerGx,dy=shifted.ScannerGy-basePoint.ScannerGy, shiftDelta,beamDelta });
Check("shift_y_changes_encoder_wait", Eq(shifted.EncoderWaitPosition-basePoint.EncoderWaitPosition,-3*Math.Abs(scale)*direction), new { before=basePoint.EncoderWaitPosition,after=shifted.EncoderWaitPosition });
Check("design_stage_and_head_unchanged", Eq(basePoint.DesignX,shifted.DesignX) && Eq(basePoint.DesignY,shifted.DesignY) && Eq(basePoint.StageX,shifted.StageX) && Eq(basePoint.StageY,shifted.StageY));
var mask = CRecipeShotMaskingPlan.Build(parameters);
var shiftedMask = CRecipeShotMaskingPlan.Build(modified);
var shiftOnly = new Dictionary<string,string>(parameters,StringComparer.OrdinalIgnoreCase){["SHIFT_OFFSET_X"]="2",["SHIFT_OFFSET_Y"]="3"};
var shiftOnlyPlan = CShotCoordinatePlanBuilder.Build(shiftOnly);
Check("shift_only_does_not_change_mask_decisions", plan.Shots.Zip(shiftOnlyPlan.Shots).All(pair => mask.EvaluateShot(pair.First).ShouldSkipLaser == mask.EvaluateShot(pair.Second).ShouldSkipLaser));
var chessParameters = new Dictionary<string,string>(parameters,StringComparer.OrdinalIgnoreCase){["MODEL1_CHESS"]="2",["MODEL1_CHESS_TYPE"]="0"};
var chess = CRecipeShotMaskingPlan.Build(chessParameters);
var model1 = plan.Shots.Where(p => parameters.GetValueOrDefault($"CELL{p.CellNo}_MODEL_TYPE","1")=="1").ToArray();
var oldKept = model1.Count(p => p.GroupColumn%2 == 0);
var newKept = model1.Count(p => !chess.EvaluateShot(p).IsChessSkipped);
Check("oneway_chess_checks_both_row_and_column", newKept == model1.Count(p => p.GroupColumn%2==0 && p.GroupRow%2==0) && newKept < oldKept,new { before=oldKept,after=newKept });
var ioRoot = Path.Combine(root,"AnalysisHarness","fixture_config",Guid.NewGuid().ToString("N"));
var offsetFile = new CReviewOffsetFile(ioRoot);
Check("no_offset_file_returns_empty", (await offsetFile.LoadLatest("missing")).Rows.Count==0);
var saved = await offsetFile.SaveNew("roundtrip", new[] {new ST_REVIEW_OFFSET_ROW(1,"A1",0.1234567,-0.75)});
var loaded = await offsetFile.LoadLatest("roundtrip");
Check("offset_roundtrip_six_decimals", loaded.Rows.Count==1 && Eq(loaded.Rows[0].ReviewOffsetX,0.123457) && Eq(loaded.Rows[0].ReviewOffsetY,-0.75),new { saved.FileName,loaded.Rows });
var legacy = new Dictionary<string,string>(parameters,StringComparer.OrdinalIgnoreCase){["CELL1_A1_REVIEW_OFFSET_X"]="1.2"};
typeof(CStationProcess).GetMethod("RemoveRecipeReviewOffsetParameters",BindingFlags.NonPublic|BindingFlags.Static)!.Invoke(null,new object[]{legacy});
Check("legacy_inline_offset_is_removed", !legacy.ContainsKey("CELL1_A1_REVIEW_OFFSET_X"));
var offsetDirectory = Path.GetDirectoryName(saved.FilePath)!;
File.WriteAllText(Path.Combine(offsetDirectory,"zz_manual.csv"),"CELLID,SHOTID,REVIEWOFFSETX,REVIEWOFFSETY\n1,A1,0.9,0.8\n");
Check("latest_selected_by_filename_not_timestamp", (await offsetFile.LoadLatest("roundtrip")).FileName == "zz_manual.csv");
File.WriteAllText(Path.Combine(offsetDirectory,"zz_zzbroken.csv"),"INVALID\n1\n");
bool rejected = false;
try { await offsetFile.LoadLatest("roundtrip"); } catch(InvalidDataException) { rejected=true; }
Check("broken_latest_throws_without_fallback",rejected);
File.WriteAllText(Path.Combine(offsetDirectory,"zz_zzznumeric.csv"),"CELLID,SHOTID,REVIEWOFFSETX,REVIEWOFFSETY\n1,A1,NaN,\n");
var nonfinite = await offsetFile.LoadLatest("roundtrip");
Check("nonfinite_offset_accepted_and_blank_defaults_zero",double.IsNaN(nonfinite.Rows[0].ReviewOffsetX) && nonfinite.Rows[0].ReviewOffsetY==0);
var type=typeof(CRootView);
var validate=type.GetMethod("ValidateShiftOffsetApply",BindingFlags.NonPublic|BindingFlags.Static)!;
var largeShift = (string?)validate.Invoke(null,new object[]{parameters,10000.0,0.0});
Check("shift_dialog_rejects_large_glass_escape",!string.IsNullOrWhiteSpace(largeShift));
var merges=typeof(CMenuCorrection).GetMethod("MergeReviewOffsetRows",BindingFlags.NonPublic|BindingFlags.Static)!;
var merged=(IReadOnlyList<ST_REVIEW_OFFSET_ROW>)merges.Invoke(null,new object[]{new[]{new ST_REVIEW_OFFSET_ROW(1,"A1",1,1),new ST_REVIEW_OFFSET_ROW(1,"A2",2,2)},new[]{new ST_CORRECTION_REVIEW_OFFSET_ROW("CELL1_A1","H01",3,4,"PENDING")}})!;
Check("offset_save_preserves_unselected_rows",merged.Count==2 && merged.Single(r=>r.ShotId=="A2").ReviewOffsetX==2 && merged.Single(r=>r.ShotId=="A1").ReviewOffsetX==3);
var h01=plan.Shots.Where(p=>p.HeadNo==1).ToArray();
var result=new { sourceCommit="05215afc0621fc38f7e29bcdf4d1b9d2bface72f",baselineCommit="a25ba3cdfd70cff5d78172d13ec957318704b1e1",checks,baseline = new{total=plan.Shots.Count,laserOn=plan.Shots.Count(p=>!mask.EvaluateShot(p).ShouldSkipLaser),chessExcluded=plan.Shots.Count(p=>mask.EvaluateShot(p).IsChessSkipped),h01Count=h01.Length,h01First=h01.First(),h01Last=h01.Last()}, newOffsetKeysInJhmi=recipe.Parameters.Count(p=>p.Key.Contains("FIRST_BEAM_OFFSET")), limitations="No equipment connections, no laser firing, no GUI click test. Shift guard is tested only as a pure static function."};
var output=Path.Combine(root,"AnalysisHarness","results.json");
File.WriteAllText(output,JsonSerializer.Serialize(result,new JsonSerializerOptions{WriteIndented=true,IncludeFields=true}));
Console.WriteLine(JsonSerializer.Serialize(result,new JsonSerializerOptions{WriteIndented=true,IncludeFields=true}));
return 0;
