(function(root){'use strict';
  const R=root.FlyingRecipe,F=root.FlyingReview,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=(v,n=2)=>Number.isFinite(v)?v.toFixed(n):'—';
  root.FlyingRecipeEditor=function({element,getParameters,onApply,download}){
    let draft=R.defaultDraft(getParameters()),dirty=false,selectedModel=1,selectedCell=1;
    const $=id=>element.querySelector('#'+id),input=(path,label,value,step='.001',type='number')=>`<label>${label}<input data-recipe-path="${path}" type="${type}" ${type==='number'?`step="${step}"`:''} value="${esc(value)}"></label>`;
    function setPath(path,value){const keys=path.split('.');let obj=draft;keys.slice(0,-1).forEach(k=>obj=obj[k]);obj[keys.at(-1)]=value;dirty=true;preview();}
    function preview(){
      const v=R.validate(draft);$('recipe-status').className='notice'+(v.errors.length?' warn':'');$('recipe-status').textContent=(dirty?'미적용 초안 · ':'편집 초안 (적용은 별도) · ')+(v.errors.length?v.errors.join(' / '):`${draft.ppid} / ${draft.cells.length} Cell / ${draft.models.length} Model / 이론 ${v.shots.toLocaleString()} Shot`)+(v.warnings.length?' · '+v.warnings.join(' / '):'');
      $('recipe-apply').disabled=!!v.errors.length;$('recipe-save').disabled=!!v.errors.length;
      const validNumbers=[draft.glassX,draft.glassY,draft.pixelSize,draft.shotPitchPixels,draft.akX,draft.akY].every(Number.isFinite);
      if(!validNumbers||draft.glassX<=0||draft.glassY<=0){$('recipe-layout').textContent='Glass·Pitch 숫자를 입력하면 미리보기를 표시합니다.';$('recipe-mask').innerHTML='';return;}
      const cellSVG=draft.cells.map(c=>{const m=draft.models[c.model-1];if(!m||![c.x,c.y,c.rotation].every(Number.isFinite))return '';const cs=R.corners(c,m,draft),ct=F.toGlobal({x:draft.akX+c.x,y:draft.akY+c.y,rotation:c.rotation},m.pixelsX*draft.pixelSize/2,m.pixelsY*draft.pixelSize/2);return `<g data-recipe-cell-select="${c.id}" tabindex="0" role="button" aria-label="C${c.id} Model${c.model} ${c.rotation}도 선택"><polygon points="${cs.map(q=>q.x+','+q.y).join(' ')}" fill="${c.id===selectedCell?'#dceff2':'#eef3f7'}" stroke="${c.id===selectedCell?'#087f8c':'#829baa'}" stroke-width="${c.id===selectedCell?3:1}"/><text x="${ct.x}" y="${ct.y}" text-anchor="middle" dominant-baseline="middle" font-size="18" fill="#173449">C${c.id}</text><title>C${c.id}: Model${c.model}, θ${c.rotation}°, Offset(${c.x},${c.y})</title></g>`;}).join('');
      $('recipe-layout').innerHTML=`<svg viewBox="-25 -55 ${draft.glassX+50} ${draft.glassY+90}" role="img" aria-label="Recipe 초안 전체 Cell 배치"><text x="0" y="-22" fill="#526b7b" font-size="23">${esc(draft.ppid)} / Global mm / Cell 클릭</text><rect width="${draft.glassX}" height="${draft.glassY}" fill="#fff" stroke="#087f8c" stroke-width="2"/>${cellSVG}</svg>`;
      $('recipe-layout').querySelectorAll('[data-recipe-cell-select]').forEach(el=>{const choose=()=>{selectedCell=Number(el.dataset.recipeCellSelect);selectedModel=draft.cells[selectedCell-1].model;render();};el.addEventListener('click',choose);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}});});
      const m=draft.models[selectedModel-1];if(!m||![m.pixelsX,m.pixelsY].every(Number.isFinite)||draft.shotPitchPixels<=0)return;
      const pitch=draft.pixelSize*draft.shotPitchPixels,half=(draft.split-1)/2*pitch/draft.split,cols=Math.floor(m.pixelsX/draft.shotPitchPixels),rows=Math.floor(m.pixelsY/draft.shotPitchPixels),width=m.pixelsX*draft.pixelSize,height=m.pixelsY*draft.pixelSize;
      if(cols*rows>10000||cols*rows<1||!Array.isArray(m.corners)||!Array.isArray(m.holes)){$('recipe-mask').textContent='모델 크기·Mask 숫자를 먼저 수정하세요.';return;}
      const sc=580/Math.max(width,height),ox=52,oy=58,marks=[];let skip=0;const count={Hole:0,Edge:0,CHESS:0};
      for(let row=1;row<=rows;row++)for(let col=1;col<=cols;col++){const mask=F.maskInfo(col,row,{...draft},m),x=ox+((col-1)*pitch+half)*sc,y=oy+((row-1)*pitch+half)*sc;if(mask.skip){skip++;mask.reasons.forEach(s=>count[s.startsWith('Hole')?'Hole':s]++);}
        marks.push(`<g><${mask.skip?'rect':'circle'} ${mask.skip?`x="${x-pitch/2*sc}" y="${y-pitch/2*sc}" width="${pitch*sc}" height="${pitch*sc}" fill="#db6d60" opacity=".32"`:`cx="${x}" cy="${y}" r="2.7" fill="#087f8c"`}/><title>열${col}/행${row}: ${mask.skip?'SKIP '+mask.reasons.join('/'):'유효 Shot'}</title></g>`);}
      const active=m.holes.slice(0,m.holeCount).filter(h=>h[2]>0&&h[3]>0).map((h,i)=>`<rect x="${ox+(h[0]+half)*sc}" y="${oy+(h[1]+half)*sc}" width="${h[2]*sc}" height="${h[3]*sc}" fill="#c95343" fill-opacity=".28" stroke="#a54135" stroke-width="1.5"/><text x="${Math.max(ox+4,Math.min(ox+(h[0]+half)*sc,ox+width*sc-54))}" y="${Math.max(oy+17,oy+(h[1]+half)*sc-5)}" font-size="14" fill="#a54135">Hole${i+1}</text>`).join('');
      const edge=F.maskInfo(1,1,draft,m).edge,edgeSVG=edge&&edge.right>edge.left&&edge.bottom>edge.top?`<rect x="${ox+(edge.left+half)*sc}" y="${oy+(edge.top+half)*sc}" width="${(edge.right-edge.left)*sc}" height="${(edge.bottom-edge.top)*sc}" fill="none" stroke="#b67818" stroke-dasharray="6 4" stroke-width="2"/>`:'';
      const W=700,H=Math.max(220,oy+height*sc+65);$('recipe-mask').innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Model${m.id} Hole Edge CHESS Masking 계산 미리보기"><defs><clipPath id="recipe-mask-clip"><rect x="${ox}" y="${oy}" width="${width*sc}" height="${height*sc}"/></clipPath></defs><text x="${ox}" y="28" font-size="20" fill="#173449">Model${m.id} / ${cols}×${rows} Shot / CHESS${draft.chess}</text><rect x="${ox}" y="${oy}" width="${width*sc}" height="${height*sc}" fill="#f0f6f8" stroke="#829baa"/><g clip-path="url(#recipe-mask-clip)">${marks.join('')}${active}${edgeSVG}</g><text x="${ox}" y="${oy+height*sc+34}" font-size="17" fill="#526b7b">유효 ${cols*rows-skip} / Skip ${skip} Shot · 모델 크기 ${num(width)}×${num(height)} mm</text></svg>`;
      $('recipe-mask-info').textContent=`Hole 접촉 ${count.Hole}, Edge 접촉 ${count.Edge}, CHESS 제외 ${count.CHESS} (중복 포함). 적색=Shot 전체 Skip, 청록=유효, 황색 점선=Edge 허용 내부. Mask 좌표 원점은 Shot 중심과 달라 표시 시 DOE 중심 오프셋 ${num(half,4)} mm를 더합니다.`;
    }
    function render(){
      const open=new Set(Array.from(element.querySelectorAll('details[open]')).map(el=>el.id)),m=draft.models[selectedModel-1]||draft.models[0];selectedModel=m.id;
      element.innerHTML=`<div class="panel-heading"><h2>전문가 · PPID Recipe / Cell / Masking</h2><span>편집 → 미리보기 → 검증 후 적용</span></div><p class="subtle">기본 운전 입력은 그대로 유지합니다. 여기서 편집하는 초안은 「Recipe 검증·적용」 전까지 운전 계산을 바꾸지 않습니다. PPID의 Model·Cell·Hole·Edge·CHESS를 반영합니다.</p><div class="recipe-actions"><label class="file-button">PPID CSV 가져오기<input id="recipe-file" type="file" accept=".csv,text/csv"></label><button id="recipe-sample" type="button">test0929 PPID 예제</button><button id="recipe-current" type="button">활성 Recipe로 되돌리기</button><button id="recipe-save" type="button">초안 PPID CSV 저장</button><button id="recipe-apply" type="button" class="primary">Recipe 검증·적용</button></div><div id="recipe-status" class="notice" role="status"></div><div id="recipe-message" role="alert" class="recipe-message"></div>
      <details id="recipe-identities" ${open.has('recipe-identities')?'open':''}><summary>PPID 이름 · Glass · 공통 Shot 조건</summary><div class="recipe-fields">${input('name','Recipe 이름',draft.name,1,'text')}${input('id','Recipe ID',draft.id,1,'text')}${input('ppid','ONLINE_PPID_NAME',draft.ppid,1,'text')}${Object.entries({glassX:'Glass X (mm)',glassY:'Glass Y (mm)',akX:'AK Margin X (mm)',akY:'AK Margin Y (mm)',pixelSize:'Design Pixel (mm)',shotPitchPixels:'PITCH (pixel)',split:'DOE 축당 분기 (1/4)',chess:'CHESS (1~5)'}).map(([k,l])=>input(k,l,draft[k],['shotPitchPixels','split','chess'].includes(k)?'1':'.001')).join('')}</div></details>
      <div class="recipe-preview-grid"><div class="visual-panel"><h3>초안 Cell 배치 · Global</h3><div id="recipe-layout"></div><p class="caption">Cell 외곽은 모델 크기와 회전을 반영합니다. C${selectedCell} 선택. 좌표는 AK Margin을 더하기 전 Cell Offset입니다.</p></div><div class="visual-panel"><h3>모델별 Masking · Cell Local</h3><label>미리보기 Model <select id="recipe-model-select">${draft.models.map(z=>`<option value="${z.id}" ${z.id===selectedModel?'selected':''}>Model${z.id}</option>`).join('')}</select></label><div id="recipe-mask"></div><p id="recipe-mask-info" class="caption"></p></div></div>
      <details id="recipe-models" ${open.has('recipe-models')?'open':''}><summary>모델 정의 · Pixel 크기 · Hole / Edge Masking</summary><p class="subtle">모델별 Masking Hole은 최대 3개입니다. 활성 개수 이후의 Hole 값은 CSV에 보존하지만 판정에서 제외합니다. ROUND 필드는 원본 코드상 사각형 Edge 제외량이며 원형 모서리가 아닙니다.</p><div class="recipe-fields">${input('models.'+(m.id-1)+'.pixelsX','Model'+m.id+' Pixel X',m.pixelsX,1)}${input('models.'+(m.id-1)+'.pixelsY','Model'+m.id+' Pixel Y',m.pixelsY,1)}${input('models.'+(m.id-1)+'.holeCount','활성 Hole 개수 (0~3)',m.holeCount,1)}</div><div class="table-wrap"><table><thead><tr><th>Hole</th><th>X (mm)</th><th>Y (mm)</th><th>폭 (mm)</th><th>높이 (mm)</th></tr></thead><tbody>${Array.from({length:3},(_,j)=>`<tr><th>${j+1}</th>${[0,1,2,3].map(k=>`<td><input aria-label="Hole${j+1} ${['X','Y','폭','높이'][k]}" data-recipe-path="models.${m.id-1}.holes.${j}.${k}" type="number" step=".001" value="${(m.holes[j]||[0,0,0,0])[k]}"></td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="table-wrap"><table><thead><tr><th>Edge 코너</th><th>제외 X (mm)</th><th>제외 Y (mm)</th></tr></thead><tbody>${['좌상','우상','좌하','우하'].map((n,j)=>`<tr><th>${n}</th>${[0,1].map(k=>`<td><input aria-label="${n} Edge ${k?'Y':'X'}" data-recipe-path="models.${m.id-1}.corners.${j}.${k}" type="number" step=".001" value="${m.corners[j][k]}"></td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="caption">8개 Edge 값이 모두 0.001 mm 이하이면 비활성. 활성 시 각 코너 max(|X|,|Y|)로 상·하·좌·우 내부를 계산합니다. 경계 접촉도 Skip입니다. Model1~5를 선택해서 각각 편집합니다.</p><button type="button" id="recipe-add-model" ${draft.models.length>=5?'disabled':''}>Model 추가 (최대5)</button></details>
      <details id="recipe-cells" ${open.has('recipe-cells')?'open':''}><summary>Cell 개별 좌표 · Model · 회전각 / 격자 자동 작성</summary><div class="recipe-grid-inputs"><label>열<input id="grid-cols" type="number" min="1" max="150" value="9"></label><label>행<input id="grid-rows" type="number" min="1" max="150" value="5"></label><label>Pitch X (mm)<input id="grid-pitch-x" type="number" value="100" step=".001"></label><label>Pitch Y (mm)<input id="grid-pitch-y" type="number" value="200" step=".001"></label><label>첫 Offset X<input id="grid-origin-x" type="number" value="0" step=".001"></label><label>첫 Offset Y<input id="grid-origin-y" type="number" value="0" step=".001"></label><label>Model<select id="grid-model">${draft.models.map(m=>`<option value="${m.id}">Model${m.id}</option>`).join('')}</select></label><button id="recipe-grid" type="button">초안 Cell 격자 생성</button></div><p class="caption">격자 생성은 초안 Cell 목록을 교체합니다. X/Y는 Cell 첫 Pixel의 AK 상대 좌표입니다. 회전은 이 첫 Pixel을 중심으로 반시계 좌표식 R(θ)을 적용합니다.</p><div class="table-wrap recipe-cell-table"><table><thead><tr><th>Cell</th><th>Offset X (mm)</th><th>Offset Y (mm)</th><th>Model</th><th>Rotation (°)</th></tr></thead><tbody>${draft.cells.map((c,i)=>`<tr data-recipe-cell="${c.id}" class="${c.id===selectedCell?'selected':''}"><th>C${c.id}</th>${['x','y'].map(k=>`<td><input aria-label="C${c.id} Offset${k.toUpperCase()}" data-recipe-path="cells.${i}.${k}" type="number" step=".001" value="${c[k]}"></td>`).join('')}<td><select aria-label="C${c.id} Model" data-recipe-path="cells.${i}.model">${draft.models.map(m=>`<option value="${m.id}" ${m.id===c.model?'selected':''}>Model${m.id}</option>`).join('')}</select></td><td><input aria-label="C${c.id} Rotation" data-recipe-path="cells.${i}.rotation" type="number" step="1" value="${c.rotation}"></td></tr>`).join('')}</tbody></table></div></details>
      <details id="recipe-csv" ${open.has('recipe-csv')?'open':''}><summary>PPID CSV 직접 붙여넣기</summary><textarea id="recipe-csv-text" spellcheck="false" aria-label="PPID SECTION NAME VALUE CSV" placeholder="PROCESS,GLASS_SIZE_X,925 ..."></textarea><button id="recipe-parse" type="button">CSV를 초안으로 읽기</button><p class="caption">SECTION,NAME,VALUE 3열 형식입니다. 원본 CSV의 Laser·Head·ReviewRule 등 미계산 항목은 보존합니다. 내보내기는 시뮬레이션 기하 Recipe 초안이며 장비 가공용 승인을 의미하지 않습니다. PPID STAGE_SPEED는 원본값을 보존하며 시뮬레이션 Y속도·Camera 조건은 운전 설정에서 별도 관리합니다.</p></details>`;
      element.querySelectorAll('[data-recipe-path]').forEach(el=>el.addEventListener('change',()=>{const path=el.dataset.recipePath;const text=['name','id','ppid'].includes(path);const value=text?el.value:el.value.trim()===''?NaN:Number(el.value);if(path.includes('.holes.')){const i=Number(path.split('.')[1]);while(draft.models[i].holes.length<3)draft.models[i].holes.push([0,0,0,0]);}setPath(path,value);}));
      $('recipe-model-select').addEventListener('change',()=>{selectedModel=Number($('recipe-model-select').value);render();});
      $('recipe-current').addEventListener('click',()=>{draft=R.defaultDraft(getParameters());dirty=false;selectedModel=1;selectedCell=1;render();});
      function importText(text){try{draft=R.parse(text,getParameters());dirty=true;selectedModel=1;selectedCell=1;render();$('recipe-message').textContent='CSV를 초안에 읽었습니다. 미리보기 확인 후 적용하세요.';}catch(e){$('recipe-message').textContent='PPID 읽기 실패 (초안과 활성 조건 유지): '+e.message;}}
      $('recipe-sample').addEventListener('click',()=>importText(root.FlyingReviewSampleCSV));
      $('recipe-parse').addEventListener('click',()=>importText($('recipe-csv-text').value));
      $('recipe-file').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>1000000){$('recipe-message').textContent='CSV는 1 MB 이하입니다.';return;}try{importText(await f.text());}catch(x){$('recipe-message').textContent=x.message;}});
      $('recipe-add-model').addEventListener('click',()=>{if(draft.models.length>=5)return;const model=R.clone(draft.models[0]);model.id=draft.models.length+1;draft.models.push(model);selectedModel=model.id;dirty=true;render();});
      $('recipe-grid').addEventListener('click',()=>{const nc=Number($('grid-cols').value),nr=Number($('grid-rows').value),px=Number($('grid-pitch-x').value),py=Number($('grid-pitch-y').value),x=Number($('grid-origin-x').value),y=Number($('grid-origin-y').value),model=Number($('grid-model').value);if(!Number.isInteger(nc)||!Number.isInteger(nr)||nc<1||nr<1||nc*nr>150||![px,py,x,y].every(Number.isFinite)||px<=0||py<=0){$('recipe-message').textContent='격자 개수는 양의 정수·총150개 이하, Pitch는 양수입니다.';return;}draft.cells=Array.from({length:nc*nr},(_,i)=>({id:i+1,x:x+i%nc*px,y:y+Math.floor(i/nc)*py,model,rotation:0}));dirty=true;selectedCell=1;render();});
      $('recipe-save').addEventListener('click',()=>{try{download(draft.ppid.replace(/[^a-zA-Z0-9_-]/g,'_')+'_recipe.csv',R.exportCSV(draft),'text/csv;charset=utf-8');}catch(e){$('recipe-message').textContent=e.message;}});
      $('recipe-apply').addEventListener('click',()=>{try{onApply(R.toParameters(draft,getParameters()));dirty=false;preview();$('recipe-message').textContent='Recipe를 적용했습니다. 기존 8개 지정점은 보존하고 유효성·시간을 다시 계산했습니다. 불가 점은 좌표 설정 또는 자동 배치로 수정하세요.';}catch(e){$('recipe-message').textContent='적용 실패 (활성 조건 유지): '+e.message;}});
      preview();
    }
    render();return {render,getDraft:()=>R.clone(draft),importText:text=>{const next=R.parse(text,getParameters());draft=next;dirty=true;selectedModel=1;selectedCell=1;render();},reset:()=>{draft=R.defaultDraft(getParameters());dirty=false;selectedModel=1;selectedCell=1;render();}};
  };
})(window);
