'use strict';const $=id=>document.getElementById(id),F=(n,k=3)=>Number.isFinite(n)?n.toFixed(k):'입력 오류';
let initial=ReviewSync.read(FIXED,SAVED_REVIEW_STATE),current=initial.data,source=initial.source,result=null;
const titles={strokeMm:'Stroke(mm)',exposureUs:'노출(µs)',blurPx:'허용blur(px)',cellPitchY:'Y Cell간격(mm)',vx:'X속도',ax:'X가속',dx:'X감속',vy:'Y등속속도',ay:'Y가속',dy:'Y감속'};
const premise=document.querySelector('details:last-of-type');if(premise)premise.innerHTML=premise.innerHTML.replace('Pitch100×200mm','Pitch X100mm / Y Cell간격은 입력값');
function render(){const p=current.params;result=ReviewCalc.calculate(FIXED,p);$('conditions').innerHTML=Object.entries(titles).map(([k,l])=>`<div class="condition">${l}<b>${F(p[k],k==='exposureUs'||k==='blurPx'?3:1)}</b></div>`).join('')+`<div class="condition">현재 선택<b>${current.mode}점 / ${current.glass+1}매</b></div>`;$('syncSource').textContent=source+(SAVED_REVIEW_STATE?' · 이 파일에 조건이 저장되어 있습니다.':' · 같은 출처에서 열린 시뮬레이터의 입력 변경을 자동 반영합니다.');$('simLink').href='FlyingReview_8Head_Simulator.html'+ReviewSync.query(current);
 if(result.inputErrors.length){$('guideBadge').textContent='입력 오류';$('guideBadge').className='pill bad';$('guideStatus').innerHTML='<div class="status fail">시뮬레이터에서 전달된 입력값을 확인해 주세요. 기본값으로 바꾸어 계산하지 않습니다.</div>';for(const id of ['timeFormula','strokeLimit','reviewFormula','reviewConclusion','guideTimeline','timelineSummary','blurFormula','blurConclusion','timingExample','xConclusion','reviewRows','cycleSummary','shotScope','checks','diagnosisText','diagnosis','transitionRows','fieldView','pointPlan','scheduleFigure','scheduleSummary','scheduleRows','idleFormula'])$(id).innerHTML='';return;}
 const r=result,m=r.modes[current.mode],g=m.groups[current.glass],d=ReviewExplain.analyze(FIXED,r,current.mode,current.glass,ReviewCalc);$('guideBadge').textContent=m.feasible?'계산상 가능':'현재 조건 불가';$('guideBadge').className='pill '+(m.feasible?'ok':'bad');$('guideStatus').innerHTML=`<div class="status ${m.feasible?'':'fail'}"><b>${d.headline}</b><p>Y 후보 ${g.yCandidateCount}/${g.nodes.length}점은 Y 범위 판정입니다. 실제 촬영 완료 수량을 뜻하지 않습니다.</p></div>`;
 $('checks').innerHTML=ReviewExplain.checkHtml(d);$('diagnosisText').innerHTML=ReviewExplain.detailHtml(FIXED,r,d);$('diagnosis').innerHTML=ReviewVisual.transition(FIXED,r,d.e,ReviewCalc);$('transitionRows').innerHTML=ReviewExplain.rowsHtml(r,current.mode);$('fieldView').innerHTML=ReviewVisual.fieldView(FIXED,r);$('pointPlan').innerHTML=ReviewExplain.planHtml(FIXED,r);
 $('scheduleFigure').innerHTML=ReviewVisual.schedule(FIXED,r,current.mode,current.glass);$('scheduleSummary').innerHTML=ReviewExplain.scheduleHtml(FIXED,r,current.mode,current.glass);$('scheduleRows').innerHTML=ReviewExplain.scheduleRowsHtml(r,current.mode,current.glass);const transfer=m.prepositions[current.glass];$('idleFormula').innerHTML=`${F(transfer.move,6)} + 0.050 + 0.020 = <b>${F(transfer.need,6)}초</b><br>남는 시간 = 180 − ${F(transfer.need,6)} = <b>${F(transfer.slack,6)}초</b><br>선배치 추가 대기 = max(0, ${F(transfer.need,6)} − 180) = <b>${F(transfer.extraTactS,6)}초</b>`;
 const triangular=r.profile.peak<p.vy-1e-8;$('timeFormula').innerHTML=triangular?`Stroke${F(p.strokeMm,1)}mm에서 최대속도는 <b>${F(r.profile.peak)}mm/s</b>입니다.<br>√(2×${F(p.strokeMm,1)}×(1/${F(p.ay,1)}+1/${F(p.dy,1)})) = <b>${F(r.processTime)}초</b>`:`${F(p.strokeMm,1)} ÷ ${F(p.vy,1)} + ${F(p.vy,1)} ÷ (2×${F(p.ay,1)}) + ${F(p.vy,1)} ÷ (2×${F(p.dy,1)}) = <b>${F(r.processTime)}초</b><br>가속 ${F(r.profile.t1)} + 등속 ${F(r.profile.t2)} + 감속 ${F(r.profile.t3)}초`;
 $('strokeLimit').innerHTML=`현재 Y속도·가감속에서30초 허용 최대 Stroke <b>${F(r.maxStroke30,3)}mm</b><br>입력 ${F(p.strokeMm,3)}mm → <b>${r.processTimePass?'30초 이내':'30초 초과'}</b>. 삼각형 운동이면 등속 가공 조건은 별도 불충족입니다.`;
 const last=g.nodes[g.nodes.length-1],pad=p.vy*(p.exposureUs/2e6+FIXED.jitterS);$('reviewFormula').innerHTML=`마지막 Head H${String(last.head).padStart(2,'0')}: ${F(last.s,3)}mm + ${F(pad,6)}mm + 감속 ${F(r.dD,3)}mm<br>= <b>최소 ${F(g.requiredStrokeMm,6)}mm</b><br>등속 유지 기준 마지막 노출 종료 ${F(g.reviewEnd,6)}초 / Stroke 종료 ${F(r.processTime,6)}초`;
 $('reviewConclusion').innerHTML=g.reviewFits?`<b>요구 ${g.nodes.length}점 모두 Y 등속 후보 범위에 있음</b><br>최소Stroke 대비 여유 ${F(p.strokeMm-g.requiredStrokeMm,3)}mm · X 준비 판정은 별도`:`<b>Stroke 내 등속 구간 ${g.yCandidateCount}/${g.nodes.length}점 · 요구수량 미충족</b><br>${g.extraStrokeMm>0?'최소 '+F(g.extraStrokeMm,3)+'mm의 추가 Stroke가 필요합니다.':'Y 가속 종료와 첫 노출 위치를 확인해야 합니다.'}`;
 $('guideTimeline').innerHTML=ReviewVisual.timeline(FIXED,r,g);$('timelineSummary').textContent=`시간0=역방향 출발. 기판 Scanner·Review 동시통과 ${F(r.physicalOverlap)}초(1500−1467mm). 입력 Stroke ${F(p.strokeMm,1)}mm, 종료StageY ${F(r.qEnd,3)}mm. 회색영역은 Stroke 밖의 필요 구간으로 실제 실행에 포함하지 않습니다.`;
 $('blurFormula').innerHTML=`${F(p.vy,1)} × ${F(p.exposureUs,3)} ÷ 125 = <b>${F(r.blurPx,6)}px = ${F(r.blurUm,6)}µm</b>`;$('blurConclusion').innerHTML=`허용 ${F(p.blurPx,3)}px → <b>${r.blurPx<=p.blurPx+1e-8?'허용 이내':'허용 초과'}</b><br>현재 Y속도의 노출 한계 ${F(r.expMaxUs,3)}µs / 현재 노출의 Y속도 한계 ${F(r.vyMax,3)}mm/s${r.expMaxUs<FIXED.minExposureUs?'<br>필요 노출이 카메라 최소2µs보다 짧습니다.':''}`;
 const e=g.edges.reduce((a,b)=>!a||b.slack<a.slack?b:a,null);$('timingExample').innerHTML=`최소 여유 H${String(e.from).padStart(2,'0')}→H${String(e.to).padStart(2,'0')}:<br>가용시간 = Y Cell 간격 ÷ Y 등속속도<br>${F(p.cellPitchY,3)} ÷ ${F(p.vy,3)} = <b>${F(e.constantSpeedGap,6)}초</b><br>ΔX${F(e.dx,3)}mm / X이동 ${F(e.move,6)}초<br>필요 준비 <b>${F(e.need,6)}초</b>`;$('xConclusion').innerHTML=`${F(e.gap,6)} − ${F(e.need,6)} = <b>여유 ${F(e.slack,6)}초</b><br>${e.valid?'X 선도착 가능':'X 이동 또는 카메라 재취득 시간 부족'}`;
 $('reviewRows').innerHTML=[2,4].flatMap(cap=>r.modes[cap].groups.map((g,i)=>`<tr${cap===current.mode&&i===current.glass?' style="background:#eef7f8"':''}><td>${cap}점</td><td>${i+1}매 / ${g.nodes.map(n=>'H'+String(n.head).padStart(2,'0')).join('→')}</td><td>${g.yCandidateCount}/${cap}</td><td>${F(g.requiredStrokeMm,3)}</td><td>${g.feasible?'가능':'불가'}</td></tr>`)).join('');$('cycleSummary').textContent=`2점:4기판 / 4점:2기판. 각 기판 역방향 가공 ${F(r.processTime)}초. 최장 선배치 ${F(m.maxPrepositionS)}초를180초 대기창에 배치하며, 선배치 추가 대기 최대 ${F(m.maxExtraTactS)}초. 180초는 현재 ReviewDone 후 다음 기판 투입까지의 여유이며 시작 간격이나 전체 장비 Tact가 아닙니다. 서로 다른 Cell8개 조건을 유지합니다.`;
 $('shotScope').textContent=`기존 test0929의 유효 Shot Y범위${F(FIXED.shotSpanY.span,1)}mm. 등속 좌표 기준 명목 Shot창 ${F(r.firstTime)}~${F(r.lastTime)}초입니다. 입력 Process Stroke는 이 좌표범위와 별도이며, 전체창이 Laser ON이라는 의미가 아닙니다. 실제 출사 중첩은 가공 스크립트·완료신호로 확인합니다.`;
}
if(!SAVED_REVIEW_STATE)ReviewSync.connection(s=>{if(!s||!s.params)return;current=ReviewSync.state(FIXED,s.params,s.mode,s.glass);source='시뮬레이터 입력 변경 반영';render();});window.getGuideState=()=>({result,snapshot:current,source});render();
