const {chromium}=require('playwright');const assert=require('assert');const fs=require('fs');const path=require('path');
(async()=>{
 const b=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),headless:true,args:['--no-sandbox']});const page=await b.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const file='file://'+path.resolve('out/FlyingReview_8Head_Simulator.html');await page.goto(file);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'preview/Simulator_desktop.png',fullPage:true});
 assert.equal(await page.locator('input[type=number]').count(),8);assert.equal(await page.locator('#pointRows tr').count(),2);assert(await page.locator('#badge').innerText()==='계산상 가능');
 await page.click('#mode4');assert.equal(await page.locator('#pointRows tr').count(),4);assert.equal(await page.locator('#glassNo').innerText(),'1 / 2 기판');await page.click('#next');assert.equal(await page.locator('#glassNo').innerText(),'2 / 2 기판');const cells=await page.locator('#pointRows tr td:nth-child(3)').allTextContents();assert.equal(new Set(cells).size,4);await page.click('#prev');
 await page.click('#play');await page.waitForTimeout(500);assert(Number(await page.locator('#time').inputValue())>0);await page.click('#play');await page.locator('#time').fill('1000');await page.locator('#time').dispatchEvent('input');assert((await page.locator('#animText').innerText()).includes('4/4'));await page.screenshot({path:'preview/Simulator_4Head.png',fullPage:true});
 await page.locator('#blurPx').fill('1');assert.equal(await page.locator('#badge').innerText(),'현재 조건 불가');assert(await page.locator('#play').isDisabled());assert((await page.locator('#status').innerText()).includes('blur'));
 await page.locator('#vy').fill('62.5');assert.equal(await page.locator('#badge').innerText(),'계산상 가능');await page.locator('#exposureUs').fill('1.25');assert.equal(await page.locator('#badge').innerText(),'현재 조건 불가');await page.click('#reset');await page.locator('#vx').fill('10');assert.equal(await page.locator('#badge').innerText(),'현재 조건 불가');await page.locator('#vx').fill('');assert.equal(await page.locator('#badge').innerText(),'입력 오류');await page.click('#reset');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'preview/Simulator_mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth)<=390);assert.equal(await page.locator('#pointRows tr').count(),4);
 await page.goto('file://'+path.resolve('out/FlyingReview_Formula_Guide.html'));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'preview/Guide_mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth)<=390);assert((await page.locator('#timingExample').innerText()).includes('0.770062'));await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'preview/Guide_desktop.png',fullPage:true});assert.equal(errors.length,0,errors.join('\n'));
 await b.close();fs.writeFileSync('preview/browser_validation.json',JSON.stringify({desktop:true,mobile390px:true,numericInputCount:8,mode2:true,mode4:true,animation:true,uniqueCells:true,rejectBlur:true,rejectExposure:true,rejectTiming:true,emptyInput:true,guide:true,consoleErrors:errors},null,2));console.log('Desktop/mobile, mode quotas, animation, blur/exposure/timing failures and guide checks passed');
})().catch(e=>{console.error(e);process.exit(1)});
