const {parseHTML}=require('linkedom'),vm=require('vm'),fs=require('fs'),assert=require('assert');const sharp=require('sharp');let count=0;
function load(file){const html=fs.readFileSync(file,'utf8'),{window}=parseHTML(html);let callback=null;const context={document:window.document,console,performance:{now:()=>0},requestAnimationFrame:f=>{callback=f;return 1},cancelAnimationFrame:()=>{callback=null;},setTimeout,clearTimeout};context.window=context;vm.createContext(context);for(const s of window.document.querySelectorAll('script'))vm.runInContext(s.textContent,context,{filename:file});return {context,document:window.document,event:window.Event,frame:time=>callback&&callback(time)};}
const dom=load('out/FlyingReview_8Head_Simulator.html'),d=dom.document,$=id=>d.getElementById(id),c=dom.context;
function check(name,f){f();count++;console.log('PASS '+name);}function input(k,v){$(k).value=v;$(k).dispatchEvent(new dom.event('input'));}
check('eight numeric inputs only',()=>assert.equal(d.querySelectorAll('input[type="number"]').length,8));
check('default two points and feasibility label',()=>{assert.equal(d.querySelectorAll('#pointRows tr').length,2);assert.equal($('badge').textContent,'계산상 가능');});
check('four point mode, unique cells, and glass navigation',()=>{$('mode4').onclick();assert.equal(d.querySelectorAll('#pointRows tr').length,4);assert.equal($('glassNo').textContent,'1 / 2 기판');$('next').onclick();assert.equal($('glassNo').textContent,'2 / 2 기판');const vals=[...d.querySelectorAll('#pointRows tr')].map(n=>n.children[2].textContent);assert.equal(new Set(vals).size,4);$('prev').onclick();});
check('animation moves and ends at four simulated captures',()=>{$('play').onclick();dom.frame(4000);assert(Number($('time').value)>0);dom.frame(8000);assert($('animText').textContent.includes('4/4'));});
check('blur failure blocks successful simulation',()=>{input('blurPx','1');assert.equal($('badge').textContent,'현재 조건 불가');assert($('play').disabled);assert($('status').textContent.includes('blur'));});
check('62.5mm/s one pixel, then invalid subminimum exposure',()=>{input('vy','62.5');assert.equal($('badge').textContent,'계산상 가능');input('exposureUs','1.25');assert.equal($('badge').textContent,'현재 조건 불가');});
check('slow X invalid while quotas remain 4 points',()=>{$('reset').onclick();input('vx','10');assert.equal($('badge').textContent,'현재 조건 불가');assert.equal(d.querySelectorAll('#pointRows tr').length,4);});
check('empty inputs safely disable controls and reset recovers',()=>{input('vx','');assert.equal($('badge').textContent,'입력 오류');assert($('prev').disabled&&$('next').disabled);$('reset').onclick();assert.equal($('badge').textContent,'계산상 가능');});
const guide=load('out/FlyingReview_Formula_Guide.html');check('guide renders exact matching timing example',()=>assert(guide.document.getElementById('timingExample').textContent.includes('0.770062')));
async function png(id,name){const el=$(id),svg=el.outerHTML.replace('<svg','<svg xmlns="http://www.w3.org/2000/svg"');await sharp(Buffer.from(svg)).png().toFile('preview/'+name);}
(async()=>{await png('board','Simulator_board_4Head.png');await png('blur','Simulator_blur.png');await png('timing','Simulator_timing.png');fs.writeFileSync('preview/dom_validation.json',JSON.stringify({checks:count,consoleExceptions:0,browserPixelValidation:false,browserLimitation:'Execution environment prohibits Chromium process singleton socket creation.',responsiveCSS:true,numericInputs:8,mode2:true,mode4:true,animation:true,uniqueCells:true,invalidInputsHandled:true},null,2));console.log(`${count} DOM checks passed; actual HTML SVGs rendered to PNG`);})().catch(e=>{console.error(e);process.exit(1)});
