(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ReviewSync=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';const KEY='flying-review-y-cell-pitch-v4';
function state(c,p,mode,glass){return {version:3,params:Object.fromEntries(Object.keys(c.defaults).map(k=>[k,p[k]])),mode:mode===4?4:2,glass:Math.max(0,Math.min((mode===4?2:4)-1,glass||0))};}
function importState(c,s){const p={...s.params};if(s.version===1)for(const k of ['settleMs','guardMs'])if(!Object.prototype.hasOwnProperty.call(p,k))p[k]=c.defaults[k];if(s.version===1||s.version===2)for(const k of Object.keys(c.defaults).filter(k=>k.startsWith('point')))if(!Object.prototype.hasOwnProperty.call(p,k))p[k]=c.defaults[k];return state(c,p,s.mode,s.glass);}
function query(s){const q=new URLSearchParams();q.set('reviewState','3');for(const [k,v] of Object.entries(s.params))q.set(k,String(v));q.set('mode',s.mode);q.set('glass',s.glass);return '?'+q.toString();}
function fromQuery(c,search){const q=new URLSearchParams(search||'');if(!q.has('reviewState'))return null;return importState(c,{version:Number(q.get('reviewState')),params:Object.fromEntries(Object.keys(c.defaults).filter(k=>q.has(k)).map(k=>[k,q.get(k).trim()===''?NaN:Number(q.get(k))])),mode:Number(q.get('mode')),glass:Number(q.get('glass'))});}
function read(c,saved){const q=fromQuery(c,typeof location!=='undefined'?location.search:'');if(q)return {data:q,source:'시뮬레이터에서 전달된 입력'};if(saved)return {data:importState(c,saved),source:'저장한 현재 조건'};try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&(s.version===1||s.version===2||s.version===3)&&s.params)return {data:importState(c,s),source:'시뮬레이터의 최근 입력'};}catch(e){}return {data:state(c,c.inquiryCase||c.defaults,c.inquiryMode||2,0),source:'문의 조건 예시 · 시뮬레이터에서 열면 현재 입력 반영'};}
function connection(onUpdate){let channel=null;try{channel=new BroadcastChannel(KEY);channel.onmessage=e=>{if(e.data&&(e.data.version===1||e.data.version===2||e.data.version===3))onUpdate(e.data);};}catch(e){}if(typeof window!=='undefined'&&window.addEventListener)window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue)try{onUpdate(JSON.parse(e.newValue));}catch(e){}});return {publish(s){try{localStorage.setItem(KEY,JSON.stringify(s));}catch(e){}if(channel)channel.postMessage(s);}};}
return {state,importState,query,fromQuery,read,connection,KEY};
});
