const {parseHTML}=require('linkedom'),vm=require('vm'),fs=require('fs'),assert=require('assert'),sharp=require('sharp');let count=0;
const storage=new Map(),channels=[];
class MockChannel{constructor(name){this.name=name;channels.push(this);}postMessage(s){for(const c of channels)if(c!==this&&c.name===this.name&&c.onmessage)c.onmessage({data:structuredClone(s)});}}
function load(file,search='',htmlOverride=null){const html=htmlOverride||fs.readFileSync(file,'utf8'),{window}=parseHTML(html);let callback=null;const context={document:window.document,console,performance:{now:()=>0},requestAnimationFrame:f=>{callback=f;return 1},cancelAnimationFrame:()=>{callback=null;},setTimeout,clearTimeout,URL,URLSearchParams,Blob,location:{search},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},BroadcastChannel:MockChannel,addEventListener:()=>{}};context.window=context;vm.createContext(context);for(const s of window.document.querySelectorAll('script'))vm.runInContext(s.textContent,context,{filename:file});return {context,document:window.document,event:window.Event,frame:time=>callback&&callback(time)};}
const dom=load('out/FlyingReview_8Head_Simulator.html'),d=dom.document,$=id=>d.getElementById(id),c=dom.context;
function check(name,f){f();count++;console.log('PASS '+name);}function input(k,v){$(k).value=v;$(k).dispatchEvent(new dom.event('input'));}function equalGuide(guide){const a=c.getReviewState(),b=guide.context.getGuideState();assert.equal(JSON.stringify(a.snapshot),JSON.stringify(b.snapshot));for(const k of ['processTime','blurPx','maxStroke30','qEnd'])assert.equal(a.result[k],b.result[k]);}
check('inquiry default: 9 inputs, 3 passes and explicit X failure',()=>{assert.equal(d.querySelectorAll('input[type="number"]').length,9);assert.equal($('strokeMm').value,'2700');assert.equal($('badge').textContent,'현재 조건 불가');assert($('status').textContent.includes('0.379초'));assert.equal(d.querySelectorAll('.checkpass').length,3);assert.equal(d.querySelectorAll('.checkfail').length,1);assert($('kpis').textContent.includes('Y 등속구간 내 후보점'));assert(!$('kpis').textContent.includes('Stroke 내 촬영'));assert.equal(d.querySelectorAll('.failedrow').length,2);assert($('diagnosis').textContent.includes('목표까지 7.180mm'));assert(!$('diagReady').disabled);$('diagReady').onclick();assert($('diagnosis').textContent.includes('X 준비 완료'));$('diagDeadline').onclick();assert($('diagnosis').textContent.includes('준비 예산이 아직'));});
check('guide query includes identical inquiry failure and point comparison',()=>{const q=$('guideLink').getAttribute('href').split('?')[1],g=load('out/FlyingReview_Formula_Guide.html','?'+q);equalGuide(g);assert(g.document.getElementById('diagnosisText').textContent.includes('2.379471'));assert(g.document.getElementById('selectionText').textContent.includes('25.5ms'));assert(g.document.getElementById('selectionText').textContent.includes('자동 적용되지'));});
check('X250 preset restores feasibility and inquiry preset keeps original points',()=>{$('xPassPreset').onclick();assert.equal($('badge').textContent,'계산상 가능');assert.equal($('strokeMm').value,'2700');assert.equal($('ax').value,'250');$('inquiryPreset').onclick();assert.equal($('badge').textContent,'현재 조건 불가');$('reset').onclick();assert.equal($('strokeMm').value,'2980');assert.equal($('badge').textContent,'계산상 가능');});
check('four point mode, all distinct cells and glass navigation',()=>{$('mode4').onclick();assert.equal(d.querySelectorAll('#pointRows tr').length,4);$('next').onclick();assert.equal($('glassNo').textContent,'2 / 2 기판');const vals=[...d.querySelectorAll('#pointRows tr')].map(n=>n.children[2].textContent);assert.equal(new Set(vals).size,4);$('prev').onclick();});
check('reverse-only animation stays in input stroke and ends at four captures',()=>{$('play').onclick();dom.frame(4000);assert($('animText').textContent.includes('역방향'));assert(!$('animText').textContent.includes('정방향'));dom.frame(8000);assert($('animText').textContent.includes('4/4'));assert($('machineText').textContent.includes('-997.500'));assert.equal($('timeLabel').textContent,'30.00 s');});
check('3000mm fails 30s; 2600mm fits; missing point does not shrink quota',()=>{input('strokeMm','3000');assert.equal($('badge').textContent,'현재 조건 불가');assert($('status').textContent.includes('30초'));input('strokeMm','2600');assert.equal($('badge').textContent,'계산상 가능');input('strokeMm','2500');assert.equal(d.querySelectorAll('#pointRows tr').length,4);assert.equal($('badge').textContent,'현재 조건 불가');assert($('overlapText').textContent.includes('3점'));assert($('play').disabled);});
check('current 9 inputs, mode and glass are passed through guide URL',()=>{$('reset').onclick();$('mode4').onclick();$('next').onclick();input('strokeMm','2800');input('exposureUs','2.4');input('blurPx','2.1');input('vx','230');input('ax','1400');input('dx','1200');input('vy','105');input('ay','600');input('dy','700');const q=$('guideLink').getAttribute('href').split('?')[1];assert(q.includes('strokeMm=2800'));const guide=load('out/FlyingReview_Formula_Guide.html','?'+q);equalGuide(guide);assert(guide.document.getElementById('conditions').textContent.includes('2800.0'));assert(guide.document.getElementById('timeFormula').textContent.includes('105.0'));assert.equal(guide.document.querySelectorAll('#reviewRows tr').length,6);});
const q=$('guideLink').getAttribute('href').split('?')[1],live=load('out/FlyingReview_Formula_Guide.html','?'+q);
check('open guide live updates input, mode and selected glass',()=>{input('strokeMm','2750');input('vy','100');input('dy','800');$('prev').onclick();equalGuide(live);assert(live.document.getElementById('syncSource').textContent.includes('変更')||live.document.getElementById('syncSource').textContent.includes('변경'));});
check('exported standalone guide embeds identical conditions without storage',()=>{const html=c.getCurrentGuideHtml();assert(html.includes('const SAVED_REVIEW_STATE={'));storage.clear();const saved=load('saved.html','',html);equalGuide(saved);assert(saved.document.getElementById('syncSource').textContent.includes('저장한 현재 조건'));input('strokeMm','2700');assert.equal(saved.context.getGuideState().snapshot.params.strokeMm,2750);});
check('guide-to-simulator return link preserves all values and selection',()=>{const g=live.context.getGuideState(),url=live.document.getElementById('simLink').getAttribute('href'),sim=load('out/FlyingReview_8Head_Simulator.html','?'+url.split('?')[1]);assert.equal(JSON.stringify(sim.context.getReviewState().snapshot),JSON.stringify(g.snapshot));});
check('invalid simulator input clears guide calculations and disables export',()=>{input('vx','');assert.equal($('badge').textContent,'입력 오류');assert($('downloadGuide').disabled);assert.equal(live.document.getElementById('guideBadge').textContent,'입력 오류');assert.equal(live.document.getElementById('guideTimeline').innerHTML,'');$('reset').onclick();assert.equal($('badge').textContent,'계산상 가능');equalGuide(live);});
check('incomplete imported state is rejected instead of silently using defaults',()=>{const guide=load('out/FlyingReview_Formula_Guide.html','?reviewState=1&strokeMm=2600');assert.equal(guide.document.getElementById('guideBadge').textContent,'입력 오류');});
check('blur, exposure and X timing constraints still reject',()=>{input('blurPx','1');assert.equal($('badge').textContent,'현재 조건 불가');input('vy','62.5');assert($('status').textContent.includes('30초'));input('exposureUs','1.25');assert($('status').textContent.includes('노출'));$('reset').onclick();input('vx','10');assert.equal($('badge').textContent,'현재 조건 불가');$('inquiryPreset').onclick();});
async function png(id,name){const svg=$(id).outerHTML.replace('<svg','<svg xmlns="http://www.w3.org/2000/svg"');await sharp(Buffer.from(svg)).flatten({background:'#ffffff'}).png().toFile('preview/'+name);}
(async()=>{for(const [id,name] of [['overlap','Process_timeline.png'],['machine','Process_machine.png'],['board','Process_cells.png'],['blur','Process_blur.png'],['timing','Process_X_timing.png'],['diagnosis','Diagnosis_transition.png'],['selectionCompare','Diagnosis_selection.png']])await png(id,name);await sharp(Buffer.from($('diagnosis').outerHTML.replace('<svg','<svg xmlns="http://www.w3.org/2000/svg"'))).flatten({background:'#ffffff'}).png().toFile('out/FlyingReview_X_Timing_Diagnosis.png');fs.writeFileSync('preview/dom_validation.json',JSON.stringify({checks:count,consoleExceptions:0,numericInputs:9,mode2:true,mode4:true,reverseOnlyAnimation:true,querySynchronization:true,liveSynchronization:true,standaloneGuideSnapshot:true,returnLinkPreservesValues:true,invalidStateRejected:true,independentCheckFlags:true,XDeadlineScrubbing:true,pointReselectionComparison:true,browserPixelValidation:false,browserLimitation:'Execution environment prohibits Chromium process singleton socket creation.'},null,2));console.log(`${count} DOM checks passed; actual HTML SVGs rendered to PNG`);})().catch(e=>{console.error(e);process.exit(1)});
