(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ReviewExplain=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';const f=(n,k=3)=>Number.isFinite(n)?n.toFixed(k):'—',head=h=>'H'+String(h).padStart(2,'0');
function worst(g){return g.edges.reduce((a,b)=>!a||b.slack<=a.slack+1e-8?b:a,null);}
function analyze(c,r,mode,glass){const m=r.modes[mode],g=m.groups[glass],e=worst(g),transfer=m.prepositions[glass],blurPass=r.blurPx<=r.p.blurPx+1e-8,exposurePass=r.p.exposureUs>=c.minExposureUs&&r.p.exposureUs<=c.maxExposureUs;
 const checks=[{key:'time',title:'① 역방향30초',pass:r.processTimePass,value:f(r.processTime)+'s / 30s',note:'Y 가속·등속·감속 포함'},{key:'y',title:'② 기판·리뷰 등속',pass:g.reviewFits&&r.boardCruiseFits,value:g.yCandidateCount+' / '+g.nodes.length+'점',note:r.boardCruiseFits?'기판1500mm 통과 + 리뷰 Y 후보':'기판1500mm의 등속 통과 불충족'},{key:'blur',title:'③ 이동 blur·노출',pass:blurPass&&exposurePass,value:f(r.blurPx,2)+'px / 허용'+f(r.p.blurPx,2)+'px',note:exposurePass?'노출 '+f(r.p.exposureUs,1)+'µs':'카메라 노출범위 밖'},{key:'x',title:'④ X 준비·취득 간격',pass:g.xTimingValid,value:e.valid?'최소 여유 '+f(e.slack)+'s':'부족 '+f(-e.slack)+'s',note:head(e.from)+'→'+head(e.to)+' · 다음 점 '+f(e.gap)+'s'}];
 checks[3].title='④ 기판 내 X 이동';checks.push({key:'idle',title:'⑤ 기판 사이 선배치',pass:transfer.valid,value:f(transfer.need)+'s / '+f(transfer.window,0)+'s',note:head(transfer.from)+'→'+head(transfer.to)+' · 추가 대기 '+f(transfer.extraTactS)+'s'});
 let headline;if(g.feasible)headline=m.feasible?'기판 내 촬영과 기판 사이 선배치 모두 통과합니다. X 선배치로 추가되는 대기는 0초입니다.':!m.prepositionFeasible?'기판 내 촬영은 가능하지만, 다음 기판 X 선배치가 180초 대기창을 초과합니다.':'이번 기판은 가능하지만, 다른 기판의 촬영 조건이 불충족입니다.';else headline='현재 조건 불충족: '+g.errors.join(' / ');
 return {m,g,e,transfer,checks,headline,cameraLimited:e.needCamera>e.needX,missDistanceMm:Math.max(0,-e.slack)*r.p.vy,readyTime:g.nodes.find(n=>n.head===e.from).expStart+e.need,deadlineTime:g.nodes.find(n=>n.head===e.to).expStart};
}
function checkHtml(d){return d.checks.map(k=>`<div class="checkcard ${k.pass?'checkpass':'checkfail'}" data-check="${k.key}"><div class="topbar"><b>${k.title}</b><span class="pill ${k.pass?'ok':'bad'}">${k.pass?'통과':'불가'}</span></div><strong>${k.value}</strong><span>${k.note}</span></div>`).join('');}
function detailHtml(c,r,d){const e=d.e;return `<b>${head(e.from)}→${head(e.to)}: 실제 선정점 ΔX ${f(e.dx,1)}mm / ΔY ${f(e.dy,1)}mm</b><br>다음 점 ${f(e.gap)}초 − 준비 ${f(e.need,6)}초 = ${e.valid?'여유 '+f(e.slack,6):'부족 '+f(-e.slack,6)}초<br><span class="small">준비 예산 종료 ${f(d.readyTime)}초 / 다음 점 명목 노출 시작 ${f(d.deadlineTime)}초. ${e.valid?'다음 점이 오기 전에 X 정지·정착 여유를 확보합니다.':'목표점 도착 마감이 준비 예산보다 빠릅니다.'} 정착50ms·Guard20ms 등 고정 설계값 기준입니다.</span>`;}
function rowsHtml(r,mode){return r.modes[mode].groups.flatMap((g,i)=>g.edges.map(e=>`<tr class="${e.valid?'':'failedrow'}"><td>${i+1}매 / ${head(e.from)}→${head(e.to)}</td><td>${f(e.dx,1)} / ${f(e.dy,1)}</td><td>${f(e.gap)}</td><td>${f(e.move)}</td><td>${f(e.need)}</td><td>${e.valid?'여유 '+f(e.slack):'부족 '+f(-e.slack)}</td><td>${e.valid?'통과':e.needX>e.gap?'X 준비 부족':'카메라 주기 부족'}</td></tr>`)).join('');}
function planHtml(c,r){const a=r.nodes.find(n=>n.head===3),b=r.nodes.find(n=>n.head===4);return `<b>스캐너 가공폭 ${f(c.scanner.fieldWidthMm,0)}mm · 리뷰 이동거리 = 두 선정점 X좌표 차이</b><br>H03: Cell${a.cell}, X${f(a.reviewX,2)}mm → H04: Cell${b.cell}, X${f(b.reviewX,2)}mm → 이동 ${f(Math.abs(b.reviewX-a.reviewX),1)}mm<br><span class="small">H04는 Cell31 열3·행1·B07, H08은 Cell35 열18·행1·B07. Head 소유권·Mask 검증을 통과한 점이며 8개 Cell 모두 다릅니다. 선정점은 입력값과 독립된 고정값입니다.</span>`;}
function scheduleHtml(c,r,mode,glass){const m=r.modes[mode],t=m.prepositions[glass];return `<div class="kpis"><div class="kpi"><span>이번 기판 후 선배치</span><b>${head(t.from)}→${head(t.to)}</b><span>ΔX ${f(t.dx,2)}mm · 선정점 X ${f(t.toX,2)}mm</span></div><div class="kpi"><span>X 이동 + 정착·여유</span><b>${f(t.need)}초</b><span>${f(t.move)} + 0.050 + 0.020초</span></div><div class="kpi"><span>180초 창의 남는 시간</span><b>${t.valid?f(t.slack):'부족 '+f(-t.slack)}초</b><span>3분 이상의 여유를 180초로 계산</span></div><div class="kpi"><span>선배치로 추가되는 대기</span><b>${f(t.extraTactS)}초</b><span>max(0, 선배치 − 180초)</span></div></div><p class="small">이번 기판의 ReviewDone·X 이동 허가 후 선배치합니다. 다음 기판 시작 전 목표점 위치·속도0·정착 완료로 XReady를 확보합니다. 초기 1회 H01 준비는 별도이며, 매 기판 Park0으로 돌아가지 않습니다.</p>${!m.motionFeasible?'<p class="error">대기창에 선배치가 들어와도, 기판 내 촬영 조건의 불충족은 해소되지 않습니다.</p>':''}`;}
function scheduleRowsHtml(r,mode,glass){const m=r.modes[mode];return m.prepositions.map((t,i)=>`<tr class="${!t.valid?'failedrow':''}"${i===glass?' style="background:#eef7f8"':''}><td>${i+1}매 / ${m.groups[i].nodes.map(n=>head(n.head)).join('→')}</td><td>${head(t.from)}→${head(t.to)}${t.wrap?' (순환복귀)':''}</td><td>${f(t.dx,2)}</td><td>${f(t.need)}</td><td>${f(t.slack)}</td><td>${f(t.extraTactS)}</td></tr>`).join('');}
return {worst,analyze,checkHtml,detailHtml,rowsHtml,planHtml,scheduleHtml,scheduleRowsHtml};
});
