(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ReviewExplain=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';const f=(n,k=3)=>Number.isFinite(n)?n.toFixed(k):'—',head=h=>'H'+String(h).padStart(2,'0');
function worst(g){return g.edges.reduce((a,b)=>!a||b.slack<=a.slack+1e-8?b:a,null);}
function analyze(c,r,mode,glass){const m=r.modes[mode],g=m.groups[glass],e=worst(g),blurPass=r.blurPx<=r.p.blurPx+1e-8,exposurePass=r.p.exposureUs>=c.minExposureUs&&r.p.exposureUs<=c.maxExposureUs;
 const checks=[{key:'time',title:'① 역방향30초',pass:r.processTimePass,value:f(r.processTime)+'s / 30s',note:'Y 가속·등속·감속 포함'},{key:'y',title:'② 기판·리뷰 등속',pass:g.reviewFits&&r.boardCruiseFits,value:g.yCandidateCount+' / '+g.nodes.length+'점',note:r.boardCruiseFits?'기판1500mm 통과 + 리뷰 Y 후보':'기판1500mm의 등속 통과 불충족'},{key:'blur',title:'③ 이동 blur·노출',pass:blurPass&&exposurePass,value:f(r.blurPx,2)+'px / 허용'+f(r.p.blurPx,2)+'px',note:exposurePass?'노출 '+f(r.p.exposureUs,1)+'µs':'카메라 노출범위 밖'},{key:'x',title:'④ X 준비·취득 간격',pass:g.xTimingValid,value:e.valid?'최소 여유 '+f(e.slack)+'s':'부족 '+f(-e.slack)+'s',note:head(e.from)+'→'+head(e.to)+' · 다음 점 '+f(e.gap)+'s'}];
 let headline;if(g.feasible)headline=m.feasible?'현재 선정점으로 이번 기판과 전체 순환 조건을 통과했습니다.':'이번 기판은 가능하지만, 다른 기판의 조건이 불충족입니다.';else headline='현재 조건 불충족: '+g.errors.join(' / ');
 return {m,g,e,checks,headline,cameraLimited:e.needCamera>e.needX,missDistanceMm:Math.max(0,-e.slack)*r.p.vy,readyTime:g.nodes.find(n=>n.head===e.from).expStart+e.need,deadlineTime:g.nodes.find(n=>n.head===e.to).expStart};
}
function checkHtml(d){return d.checks.map(k=>`<div class="checkcard ${k.pass?'checkpass':'checkfail'}" data-check="${k.key}"><div class="topbar"><b>${k.title}</b><span class="pill ${k.pass?'ok':'bad'}">${k.pass?'통과':'불가'}</span></div><strong>${k.value}</strong><span>${k.note}</span></div>`).join('');}
function detailHtml(c,r,d){const e=d.e;return `<b>${head(e.from)}→${head(e.to)}: 실제 선정점 ΔX ${f(e.dx,1)}mm / ΔY ${f(e.dy,1)}mm</b><br>다음 점 ${f(e.gap)}초 − 준비 ${f(e.need,6)}초 = ${e.valid?'여유 '+f(e.slack,6):'부족 '+f(-e.slack,6)}초<br><span class="small">준비 예산 종료 ${f(d.readyTime)}초 / 다음 점 명목 노출 시작 ${f(d.deadlineTime)}초. ${e.valid?'다음 점이 오기 전에 X 정지·정착 여유를 확보합니다.':'목표점 도착 마감이 준비 예산보다 빠릅니다.'} 정착50ms·Guard20ms 등 고정 설계값 기준입니다.</span>`;}
function rowsHtml(r,mode){return r.modes[mode].groups.flatMap((g,i)=>g.edges.map(e=>`<tr class="${e.valid?'':'failedrow'}"><td>${i+1}매 / ${head(e.from)}→${head(e.to)}</td><td>${f(e.dx,1)} / ${f(e.dy,1)}</td><td>${f(e.gap)}</td><td>${f(e.move)}</td><td>${f(e.need)}</td><td>${e.valid?'여유 '+f(e.slack):'부족 '+f(-e.slack)}</td><td>${e.valid?'통과':e.needX>e.gap?'X 준비 부족':'카메라 주기 부족'}</td></tr>`)).join('');}
function planHtml(c,r){const a=r.nodes.find(n=>n.head===3),b=r.nodes.find(n=>n.head===4);return `<b>스캐너 가공폭 ${f(c.scanner.fieldWidthMm,0)}mm · 리뷰 이동거리 = 두 선정점 X좌표 차이</b><br>H03: Cell${a.cell}, X${f(a.reviewX,2)}mm → H04: Cell${b.cell}, X${f(b.reviewX,2)}mm → 이동 ${f(Math.abs(b.reviewX-a.reviewX),1)}mm<br><span class="small">H04는 Cell31 열3·행1·B07, H08은 Cell35 열18·행1·B07. Head 소유권·Mask 검증을 통과한 점이며 8개 Cell 모두 다릅니다. 선정점은 입력값과 독립된 고정값입니다.</span>`;}
return {worst,analyze,checkHtml,detailHtml,rowsHtml,planHtml};
});
