const {parseHTML}=require('linkedom'),vm=require('vm'),fs=require('fs'),assert=require('assert'),sharp=require('sharp');let count=0;
const storage=new Map(),channels=[];
class MockChannel{constructor(name){this.name=name;channels.push(this);}postMessage(s){for(const c of channels)if(c!==this&&c.name===this.name&&c.onmessage)c.onmessage({data:structuredClone(s)});}}
function load(file,search='',htmlOverride=null){const html=htmlOverride||fs.readFileSync(file,'utf8'),{window}=parseHTML(html);let callback=null;const context={document:window.document,console,performance:{now:()=>0},requestAnimationFrame:f=>{callback=f;return 1},cancelAnimationFrame:()=>{callback=null;},setTimeout,clearTimeout,URL,URLSearchParams,Blob,location:{search},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},BroadcastChannel:MockChannel,addEventListener:()=>{}};context.window=context;vm.createContext(context);for(const s of window.document.querySelectorAll('script'))vm.runInContext(s.textContent,context,{filename:file});return {context,document:window.document,event:window.Event,frame:time=>callback&&callback(time)};}
const dom=load('out/FlyingReview_8Head_Simulator.html'),d=dom.document,$=id=>d.getElementById(id),c=dom.context;
function check(name,f){f();count++;console.log('PASS '+name);}function input(k,v){$(k).value=v;$(k).dispatchEvent(new dom.event('input'));}function equalGuide(guide){const a=c.getReviewState(),b=guide.context.getGuideState();assert.equal(JSON.stringify(a.snapshot),JSON.stringify(b.snapshot));for(const k of ['processTime','blurPx','maxStroke30','qEnd','settleS','guardS'])assert.equal(a.result[k],b.result[k]);}
check('current default has 28 inputs and five passing conditions',()=>{assert.equal(d.querySelectorAll('input[type="number"]').length,28);assert.equal($('strokeMm').value,'2700');assert.equal($('cellPitchY').value,'200');assert.equal($('ax').value,'150');assert.equal($('badge').textContent,'계산상 가능');assert.equal(d.querySelectorAll('.checkpass').length,5);assert.equal(d.querySelectorAll('.checkfail').length,0);assert.equal(d.querySelectorAll('.failedrow').length,0);assert($('fieldView').textContent.includes('102.7mm'));assert($('pointPlan').textContent.includes('Cell31'));assert($('diagnosis').textContent.includes('여유 0.297s'));assert($('diagnosis').textContent.includes('X 준비 완료'));$('diagReady').onclick();assert($('diagnosis').textContent.includes('X 준비 완료'));$('diagDeadline').onclick();});
check('guide query and point diagram reproduce current positive result',()=>{const q=$('guideLink').getAttribute('href').split('?')[1],g=load('out/FlyingReview_Formula_Guide.html','?'+q);equalGuide(g);assert(g.document.getElementById('diagnosisText').textContent.includes('1.703063'));assert(g.document.getElementById('pointPlan').textContent.includes('Cell31'));assert(g.document.getElementById('fieldView').textContent.includes('102.7mm'));assert.equal(g.document.querySelectorAll('.checkpass').length,5);});
check('two-head default distinguishes the idle 180s window from a 2s point gap',()=>{assert.equal(c.getReviewState().mode,2);assert.equal(d.querySelectorAll('#scheduleRows tr').length,4);assert($('scheduleSummary').textContent.includes('1.703초'));assert($('scheduleSummary').textContent.includes('178.297초'));assert($('scheduleFigure').textContent.includes('사용 가능 180초'));assert($('scheduleFigure').textContent.includes('ΔY 200.0mm ÷ 100.0mm/s = 2.000초'));$('next').onclick();assert($('scheduleSummary').textContent.includes('H04→H05'));$('next').onclick();$('next').onclick();assert($('scheduleSummary').textContent.includes('H08→H01'));assert($('scheduleSummary').textContent.includes('5.119초'));assert($('scheduleSummary').textContent.includes('174.881초'));$('reset').onclick();});
check('reset restores user parameters without changing point plan',()=>{input('ax','250');$('reset').onclick();assert.equal($('strokeMm').value,'2700');assert.equal($('ax').value,'150');assert.equal($('exposureUs').value,'10');assert.equal($('badge').textContent,'계산상 가능');assert($('pointPlan').textContent.includes('Cell31'));});
check('four point mode, all distinct cells and glass navigation',()=>{$('mode4').onclick();assert.equal(d.querySelectorAll('#pointRows tr').length,4);$('next').onclick();assert.equal($('glassNo').textContent,'2 / 2 기판');const vals=[...d.querySelectorAll('#pointRows tr')].map(n=>n.children[2].textContent);assert.equal(new Set(vals).size,4);$('prev').onclick();});
check('reverse-only animation stays in input stroke and ends at four captures',()=>{$('play').onclick();dom.frame(4000);assert($('animText').textContent.includes('역방향'));assert(!$('animText').textContent.includes('정방향'));dom.frame(8000);assert($('animText').textContent.includes('4/4'));assert($('machineText').textContent.includes('-717.500'));assert.equal($('timeLabel').textContent,'27.67 s');});
check('3000mm fails 30s; 2650mm fits; missing point does not shrink quota',()=>{input('strokeMm','3000');assert.equal($('badge').textContent,'현재 조건 불가');assert($('status').textContent.includes('30초'));input('strokeMm','2650');assert.equal($('badge').textContent,'계산상 가능');input('strokeMm','2500');assert.equal(d.querySelectorAll('#pointRows tr').length,4);assert.equal($('badge').textContent,'현재 조건 불가');assert($('overlapText').textContent.includes('3점'));assert($('play').disabled);});
check('current 28 inputs, mode and glass are passed through guide URL',()=>{$('reset').onclick();$('mode4').onclick();$('next').onclick();input('strokeMm','2800');input('exposureUs','2.4');input('blurPx','2.1');input('cellPitchY','180');input('vx','230');input('ax','1400');input('dx','1200');input('vy','105');input('ay','600');input('dy','700');input('settleMs','85');input('guardMs','35');const q=$('guideLink').getAttribute('href').split('?')[1];assert(q.includes('strokeMm=2800'));assert(q.includes('cellPitchY=180'));assert(q.includes('settleMs=85'));assert(q.includes('guardMs=35'));const guide=load('out/FlyingReview_Formula_Guide.html','?'+q);equalGuide(guide);assert(guide.document.getElementById('conditions').textContent.includes('2800.0'));assert(guide.document.getElementById('conditions').textContent.includes('180.0'));assert(guide.document.getElementById('timeFormula').textContent.includes('105.0'));assert.equal(guide.document.querySelectorAll('#reviewRows tr').length,6);});
const q=$('guideLink').getAttribute('href').split('?')[1],live=load('out/FlyingReview_Formula_Guide.html','?'+q);
check('open guide live updates input, mode and selected glass',()=>{input('strokeMm','2750');input('vy','100');input('dy','800');$('prev').onclick();equalGuide(live);assert(live.document.getElementById('syncSource').textContent.includes('変更')||live.document.getElementById('syncSource').textContent.includes('변경'));});
check('exported standalone guide embeds identical conditions without storage',()=>{const html=c.getCurrentGuideHtml();assert(html.includes('const SAVED_REVIEW_STATE={'));storage.clear();const saved=load('saved.html','',html);equalGuide(saved);assert(saved.document.getElementById('syncSource').textContent.includes('저장한 현재 조건'));input('strokeMm','2700');assert.equal(saved.context.getGuideState().snapshot.params.strokeMm,2750);});
check('guide-to-simulator return link preserves all values and selection',()=>{const g=live.context.getGuideState(),url=live.document.getElementById('simLink').getAttribute('href'),sim=load('out/FlyingReview_8Head_Simulator.html','?'+url.split('?')[1]);assert.equal(JSON.stringify(sim.context.getReviewState().snapshot),JSON.stringify(g.snapshot));});
check('invalid simulator input clears guide calculations and disables export',()=>{input('vx','');assert.equal($('badge').textContent,'입력 오류');assert($('downloadGuide').disabled);assert($('diagTime').disabled&&$('diagDeadline').disabled&&$('diagReady').disabled);assert.equal(live.document.getElementById('guideBadge').textContent,'입력 오류');assert.equal(live.document.getElementById('guideTimeline').innerHTML,'');$('reset').onclick();assert.equal($('badge').textContent,'계산상 가능');equalGuide(live);});
check('incomplete imported state is rejected instead of silently using defaults',()=>{const guide=load('out/FlyingReview_Formula_Guide.html','?reviewState=1&strokeMm=2600');assert.equal(guide.document.getElementById('guideBadge').textContent,'입력 오류');});
check('blur, exposure and X timing constraints still reject',()=>{input('blurPx','1');assert.equal($('badge').textContent,'현재 조건 불가');input('vy','62.5');assert($('status').textContent.includes('30초'));input('exposureUs','1.25');assert($('status').textContent.includes('노출'));$('reset').onclick();input('vx','10');assert.equal($('badge').textContent,'현재 조건 불가');$('reset').onclick();});
check('Y cell pitch changes scanner-to-scanner time instead of using a fixed 2 seconds',()=>{input('cellPitchY','180');const st=c.getReviewState(),edge=st.result.modes[st.mode].groups[st.glass].edges[0];assert.equal(edge.dy,180);assert.equal(edge.constantSpeedGap,1.8);assert($('pointRule').textContent.includes('1.800초'));assert($('timingText').textContent.includes('180.0 ÷ 100.0 = 1.800 s'));assert.equal($('badge').textContent,'계산상 가능');input('cellPitchY','170');assert.equal($('badge').textContent,'현재 조건 불가');assert($('transitionRows').textContent.includes('부족'));$('reset').onclick();});
check('parameter gauges show live pass bands and apply a calculated recovery value',()=>{assert.equal(d.querySelectorAll('#inputs input[type="range"]').length,12);assert($('cellPitchYRange').textContent.includes('통과'));input('cellPitchY','230');assert.equal($('badge').textContent,'현재 조건 불가');assert($('recovery').textContent.includes('역방향 Stroke 증가'));assert($('recovery').textContent.includes('2700.000 → 2707.000'));const b=d.querySelector('.apply-advice[data-key="strokeMm"]');assert(b);b.click();assert.equal($('strokeMm').value,'2707');assert.equal($('badge').textContent,'계산상 가능');$('reset').onclick();});
check('timeline shows physical overlap and review after scanner transit',()=>{assert($('overlap').textContent.includes('동시통과 0.330s'));assert($('overlapText').textContent.includes('20.333초'));assert($('overlapText').textContent.includes('22.165초'));const st=c.getReviewState();assert(st.result.nodes[0].expStart<st.result.scannerWindow.end);assert(st.result.nodes[3].expEnd>st.result.scannerWindow.end);});
check('idle calculations synchronize with current X inputs and selected board',()=>{$('mode2').onclick();$('next').onclick();input('vx','123');input('ax','250');equalGuide(live);const st=c.getReviewState(),gs=live.context.getGuideState();assert.equal(JSON.stringify(st.result.modes[2].prepositions),JSON.stringify(gs.result.modes[2].prepositions));assert(live.document.getElementById('idleFormula').textContent.includes(st.result.modes[2].prepositions[1].need.toFixed(6)));assert.equal(live.document.querySelectorAll('#scheduleRows tr').length,4);const saved=load('saved_idle.html','',c.getCurrentGuideHtml());equalGuide(saved);assert(saved.document.getElementById('idleFormula').textContent.includes(st.result.modes[2].prepositions[1].need.toFixed(6)));$('reset').onclick();});
check('settling and lead gauges update result diagnosis and guide formulas in real time',()=>{$('reset').onclick();input('settleMs','120');input('guardMs','80');equalGuide(live);assert($('settleMsGauge'));assert($('guardMsGauge'));assert($('timingText').textContent.includes('정착 120.0ms + 선도착 여유 80.0ms'));assert($('diagnosisText').textContent.includes('정착 120.0ms'));assert($('scheduleFigure').textContent.includes('정착120ms + 선도착80ms'));assert(live.document.getElementById('idleFormula').textContent.includes('0.120000 + 0.080000'));assert(live.document.getElementById('timingExample').textContent.includes('선도착 여유 80.0ms'));const saved=load('saved_ms.html','',c.getCurrentGuideHtml());equalGuide(saved);assert(saved.document.getElementById('timingPremise').textContent.includes('정착 120.0ms'));$('reset').onclick();assert.equal($('settleMs').value,'50');assert.equal($('guardMs').value,'20');});
check('failed settling budget offers a verified gauge reduction and becomes passing on apply',()=>{input('settleMs','400');assert.equal($('badge').textContent,'현재 조건 불가');assert($('settleMsRange').textContent.includes('통과'));const a=c.getReviewState().advice.alternatives.find(x=>x.key==='settleMs');assert(a&&a.target<400);const btn=d.querySelector('.apply-advice[data-key="settleMs"]');assert(btn);btn.click();assert.equal($('badge').textContent,'계산상 가능');equalGuide(live);$('reset').onclick();});
check('zero ms is accepted while empty or negative timing input is rejected',()=>{input('settleMs','0');input('guardMs','0');assert.equal($('badge').textContent,'계산상 가능');input('settleMs','');assert.equal($('badge').textContent,'입력 오류');input('settleMs','-1');assert.equal($('badge').textContent,'입력 오류');$('reset').onclick();});
check('legacy ten-input URLs gain only the two new default timing values',()=>{const qs=new URLSearchParams($('guideLink').getAttribute('href').split('?')[1]);qs.set('reviewState','1');qs.delete('settleMs');qs.delete('guardMs');const legacy=load('out/FlyingReview_Formula_Guide.html','?'+qs.toString()),s=legacy.context.getGuideState();assert.equal(s.snapshot.params.settleMs,50);assert.equal(s.snapshot.params.guardMs,20);assert.equal(legacy.document.getElementById('guideBadge').textContent,'계산상 가능');qs.set('reviewState','2');const incomplete=load('out/FlyingReview_Formula_Guide.html','?'+qs.toString());assert.equal(incomplete.document.getElementById('guideBadge').textContent,'입력 오류');});
check('all eight heads have independent XY gauges and a cell preview',()=>{$('reset').onclick();assert.equal(d.querySelectorAll('#pointInputs input[type="number"]').length,16);assert.equal(d.querySelectorAll('#pointInputs input[type="range"]').length,16);for(let h=1;h<=8;h++){assert($('pointX'+h+'Range').textContent.includes('통과'));assert($('pointY'+h+'Range').textContent.includes('2.7mm'));assert($('pointPreview'+h).querySelector('circle'));}assert.equal($('pointY2Gauge').step,'2.6999999999999997');});
check('moving one point gauge updates signed intervals diagram and current guide',()=>{$('pointY2Gauge').value='11.475';$('pointY2Gauge').dispatchEvent(new dom.event('input'));equalGuide(live);const r=c.getReviewState().result;assert.equal($('pointY2').value,'11.475');assert(Math.abs(r.modes[4].groups[0].edges[0].gap-2.108)<1e-9);assert(live.document.getElementById('positionRows').textContent.includes('11.475'));assert($('pointSummary2').textContent.includes('행5'));assert($('pointPreview2').textContent.includes('11.475'));$('reset').onclick();});
check('point deadline failure displays recoverable gauge target and applies it',()=>{input('pointY1','43.875');assert.equal($('badge').textContent,'현재 조건 불가');assert($('diagnosisText').textContent.includes('156.800'));assert($('pointY1Range').textContent.includes('27.675'));const a=c.getReviewState().advice.alternatives.find(x=>x.key==='pointY1');assert(a);const b=d.querySelector('.apply-advice[data-key="pointY1"]');assert(b);b.click();assert.equal($('badge').textContent,'계산상 가능');equalGuide(live);$('reset').onclick();});
check('wrong ownership and off-grid locations cannot appear as passing captures',()=>{input('pointX4','1.35');assert.equal($('badge').textContent,'현재 조건 불가');assert($('pointSummary4').textContent.includes('불가'));assert($('status').textContent.includes('유효 B07'));input('pointX4','6.75');input('pointX1','5');assert.equal($('badge').textContent,'현재 조건 불가');assert($('status').textContent.includes('2.7mm'));$('reset').onclick();});
check('snapshot and return links retain all sixteen measurement coordinates',()=>{input('pointX4','9.45');input('pointY2','11.475');const q=$('guideLink').getAttribute('href');assert(q.includes('pointX4=9.45')&&q.includes('pointY2=11.475'));const saved=load('point_snapshot.html','',c.getCurrentGuideHtml());equalGuide(saved);assert(saved.document.getElementById('positionRows').textContent.includes('9.450'));const url=saved.document.getElementById('simLink').getAttribute('href'),sim=load('out/FlyingReview_8Head_Simulator.html','?'+url.split('?')[1]);assert.equal(sim.document.getElementById('pointX4').value,'9.45');assert.equal(sim.document.getElementById('pointY2').value,'11.475');$('reset').onclick();});
check('legacy twelve-input URL gets point defaults while current incomplete state fails',()=>{const q=new URLSearchParams($('guideLink').getAttribute('href').split('?')[1]);q.set('reviewState','2');for(const key of [...q.keys()])if(key.startsWith('point'))q.delete(key);const g=load('out/FlyingReview_Formula_Guide.html','?'+q);assert.equal(g.document.getElementById('guideBadge').textContent,'계산상 가능');assert.equal(g.context.getGuideState().snapshot.params.pointX8,47.25);q.set('reviewState','3');assert.equal(load('out/FlyingReview_Formula_Guide.html','?'+q).document.getElementById('guideBadge').textContent,'입력 오류');});
async function png(id,name){const svg=$(id).outerHTML.replace('<svg','<svg xmlns="http://www.w3.org/2000/svg"');await sharp(Buffer.from(svg)).flatten({background:'#ffffff'}).png().toFile('preview/'+name);}
(async()=>{for(const [id,name] of [['overlap','Process_timeline.png'],['machine','Process_machine.png'],['board','Process_cells.png'],['blur','Process_blur.png'],['timing','Process_X_timing.png'],['diagnosis','Diagnosis_transition.png'],['fieldView','Current_field.png'],['scheduleFigure','Interboard_schedule.png']])await png(id,name);const svg=$('scheduleFigure').outerHTML.replace('<svg','<svg xmlns="http://www.w3.org/2000/svg"');await sharp(Buffer.from(svg)).png().toFile('out/FlyingReview_X_Timing_Diagnosis.png');fs.writeFileSync('preview/dom_validation.json',JSON.stringify({interboardPreposition:true,idleWindow180:true,wrapIncluded:true,startupOnceOnly:true,extraTactS:0,checks:count,consoleExceptions:0,numericInputs:28,yCellPitchInput:true,mode2:true,mode4:true,reverseOnlyAnimation:true,querySynchronization:true,liveSynchronization:true,standaloneGuideSnapshot:true,returnLinkPreservesValues:true,invalidStateRejected:true,independentCheckFlags:true,XDeadlineScrubbing:true,nearbyValidPointPlan:true,physicalOverlapShown:true,browserPixelValidation:false,browserLimitation:'Execution environment prohibits Chromium process singleton socket creation.'},null,2));console.log(`${count} DOM checks passed; actual HTML SVGs rendered to PNG`);})().catch(e=>{console.error(e);process.exit(1)});
