// Optional full-browser checks; requires a Chromium-capable execution environment.
const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path');
(async()=>{const b=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),headless:true,args:['--no-sandbox']}),p=await b.newPage({viewport:{width:1440,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('file://'+path.resolve('out/FlyingReview_8Head_Simulator.html'));await p.evaluate(()=>document.fonts.ready);assert.equal(await p.locator('input[type=number]').count(),9);assert.equal(await p.locator('#badge').innerText(),'계산상 가능');assert.equal(await p.locator('.checkpass').count(),5);assert.equal(await p.locator('.checkfail').count(),0);await p.screenshot({path:'preview/Process_desktop.png',fullPage:true});
 await p.click('#reset');await p.click('#mode4');await p.click('#next');assert.equal(await p.locator('#glassNo').innerText(),'2 / 2 기판');await p.locator('#strokeMm').fill('3000');assert.equal(await p.locator('#badge').innerText(),'현재 조건 불가');await p.locator('#strokeMm').fill('2650');assert.equal(await p.locator('#badge').innerText(),'계산상 가능');await p.locator('#strokeMm').fill('2500');assert(await p.locator('#play').isDisabled());assert.equal(await p.locator('#pointRows tr').count(),4);assert((await p.locator('#overlapText').innerText()).includes('3점'));
 await p.click('#reset');await p.click('#mode4');await p.getByText('기판 내 촬영 상세 · X 이동과 가공·리뷰 중첩').click();await p.locator('#time').fill('1000');await p.locator('#time').dispatchEvent('input');assert((await p.locator('#animText').innerText()).includes('4/4'));assert.equal(await p.locator('#timeLabel').innerText(),'27.67 s');await p.locator('#strokeMm').fill('2800');await p.locator('#exposureUs').fill('2.4');await p.locator('#blurPx').fill('2.1');await p.locator('#vx').fill('230');await p.locator('#ay').fill('600');
 const state=await p.evaluate(()=>getReviewState().snapshot),g=await b.newPage();g.on('pageerror',e=>errors.push(e.message));const href=await p.locator('#guideLink').getAttribute('href');await g.goto('file://'+path.resolve('out')+'/'+href);assert.equal(JSON.stringify(await g.evaluate(()=>getGuideState().snapshot)),JSON.stringify(state));
 const download=await Promise.all([p.waitForEvent('download'),p.click('#downloadGuide')]);const saved=path.resolve('preview/Current_condition_guide.html');await download[0].saveAs(saved);await g.goto('file://'+saved);assert.equal(JSON.stringify(await g.evaluate(()=>getGuideState().snapshot)),JSON.stringify(state));await g.screenshot({path:'preview/Guide_current_condition.png',fullPage:true});
 await p.setViewportSize({width:390,height:844});await p.screenshot({path:'preview/Process_mobile.png',fullPage:true});assert(await p.evaluate(()=>document.documentElement.scrollWidth)<=390);await g.setViewportSize({width:390,height:844});await g.screenshot({path:'preview/Guide_mobile.png',fullPage:true});assert(await g.evaluate(()=>document.documentElement.scrollWidth)<=390);assert.equal(errors.length,0,errors.join('\n'));await b.close();fs.writeFileSync('preview/browser_validation.json',JSON.stringify({desktop:true,mobile390px:true,numericInputCount:9,strokeBoundary:true,querySynchronization:true,standaloneSnapshot:true,consoleErrors:errors},null,2));console.log('Browser checks passed');
})().catch(e=>{console.error(e);process.exit(1)});
