const {parseHTML}=require('linkedom'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),t=require('node:test'),A=require('node:assert/strict');
function app(){const html=fs.readFileSync(path.join(__dirname,'../FlyingReview_8Head_Simulator.html'),'utf8'),{window}=parseHTML(html);window.requestAnimationFrame=()=>0;window.setTimeout=()=>0;window.console=console;const ctx=vm.createContext(window);for(const s of window.document.querySelectorAll('script'))vm.runInContext(s.textContent,ctx);return window;}
t('offline app initializes with exactly essential numeric controls',()=>{const w=app();A.equal(w.document.querySelectorAll('[data-param]').length,8);A.equal(w.document.querySelectorAll('[data-cap]').length,2);A.match(w.document.getElementById('summary').textContent,/4점 계산상 가능/);A.equal(w.document.getElementById('error').hidden,true);});
t('full 45 Cell map and real moving glass render',()=>{const w=app();A.equal(w.FlyingReviewApp.getState().a.g.cells.length,45);A.match(w.document.getElementById('scene').innerHTML,/ATM Box/);A.match(w.document.getElementById('scene').innerHTML,/globalMap/);A.equal(w.document.querySelectorAll('.head').length,8);});
t('history retained across Glass and rewind, restart clears',()=>{const w=app(),api=w.FlyingReviewApp;api.seek(30);A.equal(w.document.querySelectorAll('.head.done').length,4);const span=api.getState().a.r.profile.total+1;api.seek(span+26);A.equal(w.document.querySelectorAll('.head.done').length,6);api.seek(0);A.equal(w.document.querySelectorAll('.head.done').length,6);api.restart();A.equal(w.document.querySelectorAll('.head.done').length,0);});
t('cycle completion retains all 8 and only next start clears',()=>{const w=app(),api=w.FlyingReviewApp;api.seek(1000);A.equal(w.document.querySelectorAll('.head.done').length,8);A.match(w.document.getElementById('narrative').textContent,/사이클을 완료/);w.document.getElementById('play').click();A.equal(w.document.querySelectorAll('.head.done').length,0);A.equal(api.getState().cycle,2);});
t('two-point operation has exactly four Glass groups',()=>{const w=app();w.FlyingReviewApp.setMode(2);A.equal(w.FlyingReviewApp.getState().cap,2);A.match(w.document.getElementById('summary').textContent,/4 Glass/);});
t('blur failure blocks play and shows exact actionable advice',()=>{const w=app();w.FlyingReviewApp.setInput({blurPx:1});A.equal(w.document.getElementById('play').disabled,true);A.match(w.document.getElementById('advice').textContent,/62.50/);w.document.querySelector('[data-tip]').click();A.equal(w.FlyingReviewApp.getState().a.input.vy,62.5);A.equal(w.document.getElementById('play').disabled,false);});
t('X too slow shows a corrective speed without DOM exception',()=>{const w=app();w.FlyingReviewApp.setInput({vx:30});A.match(w.document.getElementById('advice').textContent,/구간 X/);A.equal(w.document.getElementById('play').disabled,true);});
t('duplicate Cell selection rejected and original result is not silently valid',()=>{const w=app(),d=JSON.parse(JSON.stringify(w.FlyingReviewApp.getState().a.defs));d[1].cell=d[0].cell;A.equal(w.FlyingReviewApp.setPoints(d),false);A.equal(w.document.getElementById('error').hidden,false);A.match(w.document.getElementById('error').textContent,/서로 다른 Cell/);A.equal(w.document.getElementById('play').disabled,true);w.document.getElementById('auto').click();A.equal(w.document.getElementById('error').hidden,true);});
t('map picking avoids Cells used by other heads and all masked points',()=>{const w=app(),s=w.document.getElementById('scene');s.getBoundingClientRect=()=>({left:0,top:0,width:1040,height:690});const e=new w.Event('click');Object.assign(e,{clientX:642,clientY:190});s.dispatchEvent(e);const a=w.FlyingReviewApp.getState().a;A.equal(new Set(a.defs.map(n=>n.cell)).size,8);A.ok(a.r.nodes.every(n=>n.geometryValid));A.match(w.document.getElementById('pointMessage').textContent,/중복 Cell/);});
t('guide presents fps separately from exposure and effective optics assumptions',()=>{const h=fs.readFileSync(path.join(__dirname,'../FlyingReview_Formula_Guide.html'),'utf8');for(const s of ['0.125','1.25','62.5','18.5','BslEffectiveExposureTime','200 mm tube lens','전수검사','12.23'])A.ok(h.includes(s));});
t('invalid input cannot export a stale successful calculation',()=>{const w=app();w.FlyingReviewApp.setInput({exposureUs:1.25});A.equal(w.document.getElementById('export').disabled,true);w.FlyingReviewApp.setInput({exposureUs:2});A.equal(w.document.getElementById('export').disabled,false);});
