/* Meaningful expert editor interaction checks; no browser pixel/device claim. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),{parseHTML}=require('linkedom');
const html=fs.readFileSync(path.join(__dirname,'../FlyingReview_8Head_Simulator.html'),'utf8'),{window:w,document}=parseHTML(html);
Object.defineProperty(w.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this.querySelector('option[selected]')?.value||this.querySelector('option')?.value||'';},set(v){this.querySelectorAll('option').forEach(o=>o.toggleAttribute('selected',String(o.value)===String(v)));}});
Object.defineProperty(w.HTMLInputElement.prototype,'checked',{configurable:true,get(){return this.hasAttribute('checked');},set(v){this.toggleAttribute('checked',!!v);}});
const downloads=[],ctx=vm.createContext({document,console,Blob,URL:{createObjectURL:b=>{downloads.push(b);return 'blob:test';},revokeObjectURL(){}},setTimeout:()=>0,requestAnimationFrame:()=>{}});ctx.window=ctx;
for(const s of document.querySelectorAll('script'))vm.runInContext(s.textContent,ctx);
const $=id=>document.getElementById(id),click=el=>el.dispatchEvent(new w.Event('click',{bubbles:true})),change=el=>el.dispatchEvent(new w.Event('change',{bubbles:true})),state=()=>ctx.FlyingReviewApp.getState();let count=0;
const field=(path,value)=>{const el=document.querySelector('[data-recipe-path="'+path+'"]');assert.ok(el,path);el.value=value;change(el);};
const test=(name,fn)=>{fn();count++;console.log('PASS',name);};
test('expert launcher opens separate full-width tab, basic controls remain minimal',()=>{assert.equal($('panel-recipe').hidden,true);assert.equal($('basic-parameters').querySelectorAll('[data-param]').length,3);click($('open-recipe'));assert.equal($('panel-recipe').hidden,false);assert.equal($('recipe-cells').hasAttribute('open'),false);assert.equal(document.querySelectorAll('[data-recipe-cell]').length,45);});
test('full PPID example loads into draft without touching active state or cycle ledger',()=>{ctx.FlyingReviewApp.seek(30);const before=JSON.stringify(state());click($('recipe-sample'));assert.equal(JSON.stringify(state()),before);assert.ok($('recipe-status').textContent.includes('미적용'));assert.equal($('recipe-apply').disabled,false);});
test('per-cell model/rotation and local masking preview update while active geometry stays fixed',()=>{field('cells.0.model',2);field('cells.0.x',30);field('cells.0.rotation',90);assert.equal(state().parameters.models,null);assert.ok($('recipe-layout').innerHTML.includes('θ90'));assert.equal($('recipe-apply').disabled,false);$('recipe-model-select').value=2;change($('recipe-model-select'));assert.ok($('recipe-mask').textContent.includes('4×8'));assert.ok($('recipe-mask-info').textContent.includes('Edge'));});
test('apply is atomic, preserves requests, resets cycle and recalculates model bounds',()=>{const points=JSON.stringify(state().points);click($('recipe-apply'));assert.equal(state().parameters.cellLayout[0].rotation,90);assert.equal(state().parameters.cellLayout[0].model,2);assert.equal(state().parameters.models.length,5);assert.equal(JSON.stringify(state().points),points);assert.equal(state().covered.length,0);assert.equal(document.querySelector('.map-cell[data-cell="1"]>rect').getAttribute('width'),'12.959999999999999');assert.ok(document.querySelector('.map-cell[data-cell="1"]>rect').getAttribute('transform').includes('90'));assert.equal($('error-box').hidden,true);assert.ok($('notice').textContent.includes('미성립'));});
test('invalid draft cannot replace active geometry and can be corrected',()=>{const before=JSON.stringify(state());field('cells.0.x',-100);assert.equal($('recipe-apply').disabled,true);assert.ok($('recipe-status').textContent.includes('Glass 밖'));click($('recipe-apply'));assert.equal(JSON.stringify(state()),before);field('cells.0.x',30);assert.equal($('recipe-apply').disabled,false);});
test('bad PPID parse leaves edited draft and active plan intact',()=>{const before=JSON.stringify(state()),old=$('recipe-layout').innerHTML;$('recipe-csv-text').value='PROCESS,PIXEL_SIZE,';click($('recipe-parse'));assert.ok($('recipe-message').textContent.includes('읽기 실패'));assert.equal(JSON.stringify(state()),before);assert.equal($('recipe-layout').innerHTML,old);});
test('grid generator changes only draft and keeps one Head per Cell example reproducible',()=>{$('grid-cols').value=8;$('grid-pitch-x').value=110;click($('recipe-grid'));assert.equal(document.querySelectorAll('[data-recipe-cell]').length,40);assert.equal(state().parameters.cellLayout.length,45);click($('recipe-apply'));assert.equal(state().parameters.cellLayout.length,40);assert.equal(document.querySelectorAll('.moving-cell').length,40);assert.equal($('error-box').hidden,true);});
test('masking all Model1 points blocks execution but editor remains usable',()=>{$('recipe-model-select').value=1;change($('recipe-model-select'));field('models.0.holeCount',1);field('models.0.holes.0.0',-10);field('models.0.holes.0.1',-10);field('models.0.holes.0.2',200);field('models.0.holes.0.3',200);click($('recipe-apply'));assert.equal(state().maxPerPass,0);assert.equal($('play').disabled,true);assert.equal($('error-box').hidden,true);assert.ok($('recipe-editor').textContent.includes('Recipe 검증·적용'));click($('recipe-current'));assert.equal($('recipe-apply').disabled,false);});
test('CSV draft export preserves extra PPID rows and the active Hole count',()=>{click($('recipe-save'));assert.equal(downloads.length,1);});
test('light palette covers controls and all SVG backgrounds with darker state marks',()=>{const style=document.querySelector('style').textContent;assert.ok(style.includes('color-scheme:light'));assert.ok(style.includes('--formula-graph-bg:#f3f8fb'));assert.equal(document.querySelector('#machine-scene svg>rect').getAttribute('fill'),'#f8fbfd');assert.equal(document.querySelector('#global-map svg>rect').getAttribute('fill'),'#f8fbfd');assert.ok(document.querySelectorAll('#recipe-layout svg').length);});
click($('reset-params'));click($('recipe-sample'));field('cells.0.x',60);field('cells.0.rotation',90);click($('recipe-apply'));
const point=ctx.FlyingReviewApp.getState().points.find(p=>p.head===1);for(const [key,val] of [['cell',1],['col',3],['row',2],['beam',7]]){const e=document.querySelector('tr[data-head="1"] [data-point="'+key+'"]');e.value=val;change(e);}
$('detail-head').value=1;$('follow-shot').checked=false;change($('detail-head'));ctx.FlyingReviewApp.seek(24);
test('rotated Cell detail projects fixed global Y plane into local vertical line',()=>{const line=$('detail-review-plane').querySelector('line');assert.ok(Math.abs(Number(line.getAttribute('x1'))-Number(line.getAttribute('x2')))<1e-6);assert.notEqual(line.getAttribute('y1'),line.getAttribute('y2'));assert.ok($('cell-detail').textContent.includes('θ90°'));assert.ok($('formula-guide').textContent.includes('72.1250'));});
downloads[0].text().then(text=>{test('exported PPID round trips actual unmodelled Laser field',()=>{const d=ctx.FlyingRecipe.parse(text,ctx.FlyingReview.copyDefaults());assert.equal(d.cells.length,40);assert.equal(d.models[0].holes[0][2],200);assert.equal(d.rows.find(r=>r[1]==='H01_LASER_POWER')[2],'10');});console.log(count+' expert editor DOM tests passed.');}).catch(e=>{console.error(e);process.exitCode=1;});
